using DevExpress.XtraEditors;

namespace NuanSystem.WinForms.Forms.TaxCatalogs.RetentionConcepts;

partial class RetentionConceptEditForm
{
    private System.ComponentModel.IContainer components = null;

    private void InitializeComponent()
    {
        lblCode = new LabelControl();
        txtCode = new TextEdit();
        lblName = new LabelControl();
        txtName = new TextEdit();
        lblRetentionType = new LabelControl();
        lueRetentionType = new LookUpEdit();
        lblSriCode = new LabelControl();
        txtSriCode = new TextEdit();
        lblPercent = new LabelControl();
        spnPercent = new SpinEdit();
        lblDescription = new LabelControl();
        memDescription = new MemoEdit();
        chkAppliesIva = new CheckEdit();
        chkAppliesIncome = new CheckEdit();
        chkIsActive = new CheckEdit();
        btnCancel = new SimpleButton();
        btnSave = new SimpleButton();
        ((System.ComponentModel.ISupportInitialize)txtCode.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtName.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueRetentionType.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtSriCode.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)spnPercent.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)memDescription.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkAppliesIva.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkAppliesIncome.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkIsActive.Properties).BeginInit();
        SuspendLayout();
        lblCode.Appearance.Font = new Font("Segoe UI", 9F);
        lblCode.Appearance.Options.UseFont = true;
        lblCode.Location = new Point(28, 29);
        lblCode.Name = "lblCode";
        lblCode.Size = new Size(39, 15);
        lblCode.TabIndex = 0;
        lblCode.Text = "Codigo";
        txtCode.Location = new Point(176, 26);
        txtCode.Name = "txtCode";
        txtCode.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        txtCode.Properties.Appearance.Options.UseFont = true;
        txtCode.Properties.AutoHeight = false;
        txtCode.Properties.MaxLength = 30;
        txtCode.Size = new Size(150, 22);
        txtCode.TabIndex = 1;
        lblName.Appearance.Font = new Font("Segoe UI", 9F);
        lblName.Appearance.Options.UseFont = true;
        lblName.Location = new Point(28, 60);
        lblName.Name = "lblName";
        lblName.Size = new Size(44, 15);
        lblName.TabIndex = 2;
        lblName.Text = "Concepto";
        txtName.Location = new Point(176, 57);
        txtName.Name = "txtName";
        txtName.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        txtName.Properties.Appearance.Options.UseFont = true;
        txtName.Properties.AutoHeight = false;
        txtName.Properties.MaxLength = 160;
        txtName.Size = new Size(360, 22);
        txtName.TabIndex = 3;
        lblRetentionType.Appearance.Font = new Font("Segoe UI", 9F);
        lblRetentionType.Appearance.Options.UseFont = true;
        lblRetentionType.Location = new Point(28, 91);
        lblRetentionType.Name = "lblRetentionType";
        lblRetentionType.Size = new Size(91, 15);
        lblRetentionType.TabIndex = 4;
        lblRetentionType.Text = "Tipo de retencion";
        lueRetentionType.Location = new Point(176, 88);
        lueRetentionType.Name = "lueRetentionType";
        lueRetentionType.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        lueRetentionType.Properties.Appearance.Options.UseFont = true;
        lueRetentionType.Properties.AutoHeight = false;
        lueRetentionType.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
        lueRetentionType.Properties.NullText = "";
        lueRetentionType.Size = new Size(360, 22);
        lueRetentionType.TabIndex = 5;
        lblSriCode.Appearance.Font = new Font("Segoe UI", 9F);
        lblSriCode.Appearance.Options.UseFont = true;
        lblSriCode.Location = new Point(28, 122);
        lblSriCode.Name = "lblSriCode";
        lblSriCode.Size = new Size(59, 15);
        lblSriCode.TabIndex = 6;
        lblSriCode.Text = "Codigo SRI";
        txtSriCode.Location = new Point(176, 119);
        txtSriCode.Name = "txtSriCode";
        txtSriCode.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        txtSriCode.Properties.Appearance.Options.UseFont = true;
        txtSriCode.Properties.AutoHeight = false;
        txtSriCode.Properties.MaxLength = 30;
        txtSriCode.Size = new Size(150, 22);
        txtSriCode.TabIndex = 7;
        lblPercent.Appearance.Font = new Font("Segoe UI", 9F);
        lblPercent.Appearance.Options.UseFont = true;
        lblPercent.Location = new Point(348, 122);
        lblPercent.Name = "lblPercent";
        lblPercent.Size = new Size(61, 15);
        lblPercent.TabIndex = 8;
        lblPercent.Text = "Porcentaje";
        spnPercent.Location = new Point(436, 119);
        spnPercent.Name = "spnPercent";
        spnPercent.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        spnPercent.Properties.Appearance.Options.UseFont = true;
        spnPercent.Properties.Appearance.Options.UseTextOptions = true;
        spnPercent.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
        spnPercent.Properties.AutoHeight = false;
        spnPercent.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
        spnPercent.Properties.DisplayFormat.FormatString = "n2";
        spnPercent.Properties.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
        spnPercent.Properties.EditFormat.FormatString = "n2";
        spnPercent.Properties.EditFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
        spnPercent.Properties.MaskSettings.Set("mask", "n2");
        spnPercent.Size = new Size(100, 22);
        spnPercent.TabIndex = 9;
        lblDescription.Appearance.Font = new Font("Segoe UI", 9F);
        lblDescription.Appearance.Options.UseFont = true;
        lblDescription.Location = new Point(28, 153);
        lblDescription.Name = "lblDescription";
        lblDescription.Size = new Size(62, 15);
        lblDescription.TabIndex = 10;
        lblDescription.Text = "Descripcion";
        memDescription.Location = new Point(176, 150);
        memDescription.Name = "memDescription";
        memDescription.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        memDescription.Properties.Appearance.Options.UseFont = true;
        memDescription.Properties.MaxLength = 300;
        memDescription.Size = new Size(360, 78);
        memDescription.TabIndex = 11;
        chkAppliesIva.Location = new Point(174, 238);
        chkAppliesIva.Name = "chkAppliesIva";
        chkAppliesIva.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        chkAppliesIva.Properties.Appearance.Options.UseFont = true;
        chkAppliesIva.Properties.Caption = "Aplica IVA";
        chkAppliesIva.Size = new Size(96, 20);
        chkAppliesIva.TabIndex = 12;
        chkAppliesIncome.Location = new Point(286, 238);
        chkAppliesIncome.Name = "chkAppliesIncome";
        chkAppliesIncome.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        chkAppliesIncome.Properties.Appearance.Options.UseFont = true;
        chkAppliesIncome.Properties.Caption = "Aplica renta";
        chkAppliesIncome.Size = new Size(110, 20);
        chkAppliesIncome.TabIndex = 13;
        chkIsActive.EditValue = true;
        chkIsActive.Location = new Point(412, 238);
        chkIsActive.Name = "chkIsActive";
        chkIsActive.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        chkIsActive.Properties.Appearance.Options.UseFont = true;
        chkIsActive.Properties.Caption = "Activo";
        chkIsActive.Size = new Size(75, 20);
        chkIsActive.TabIndex = 14;
        btnCancel.Appearance.BackColor = Color.FromArgb(99, 110, 114);
        btnCancel.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        btnCancel.Appearance.ForeColor = Color.White;
        btnCancel.Appearance.Options.UseBackColor = true;
        btnCancel.Appearance.Options.UseFont = true;
        btnCancel.Appearance.Options.UseForeColor = true;
        btnCancel.DialogResult = DialogResult.Cancel;
        btnCancel.Location = new Point(330, 286);
        btnCancel.LookAndFeel.Style = DevExpress.LookAndFeel.LookAndFeelStyle.Flat;
        btnCancel.LookAndFeel.UseDefaultLookAndFeel = false;
        btnCancel.Name = "btnCancel";
        btnCancel.Size = new Size(100, 36);
        btnCancel.TabIndex = 15;
        btnCancel.Text = "Cancelar";
        btnSave.Appearance.BackColor = Color.FromArgb(0, 184, 148);
        btnSave.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        btnSave.Appearance.ForeColor = Color.White;
        btnSave.Appearance.Options.UseBackColor = true;
        btnSave.Appearance.Options.UseFont = true;
        btnSave.Appearance.Options.UseForeColor = true;
        btnSave.Location = new Point(436, 286);
        btnSave.LookAndFeel.Style = DevExpress.LookAndFeel.LookAndFeelStyle.Flat;
        btnSave.LookAndFeel.UseDefaultLookAndFeel = false;
        btnSave.Name = "btnSave";
        btnSave.Size = new Size(100, 36);
        btnSave.TabIndex = 16;
        btnSave.Text = "Guardar";
        AcceptButton = btnSave;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        CancelButton = btnCancel;
        ClientSize = new Size(564, 344);
        Controls.Add(lblCode);
        Controls.Add(txtCode);
        Controls.Add(lblName);
        Controls.Add(txtName);
        Controls.Add(lblRetentionType);
        Controls.Add(lueRetentionType);
        Controls.Add(lblSriCode);
        Controls.Add(txtSriCode);
        Controls.Add(lblPercent);
        Controls.Add(spnPercent);
        Controls.Add(lblDescription);
        Controls.Add(memDescription);
        Controls.Add(chkAppliesIva);
        Controls.Add(chkAppliesIncome);
        Controls.Add(chkIsActive);
        Controls.Add(btnCancel);
        Controls.Add(btnSave);
        Font = new Font("Segoe UI", 9F);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "RetentionConceptEditForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "Concepto de retencion";
        ((System.ComponentModel.ISupportInitialize)txtCode.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtName.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueRetentionType.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtSriCode.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)spnPercent.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)memDescription.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkAppliesIva.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkAppliesIncome.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkIsActive.Properties).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    private LabelControl lblCode;
    private TextEdit txtCode;
    private LabelControl lblName;
    private TextEdit txtName;
    private LabelControl lblRetentionType;
    private LookUpEdit lueRetentionType;
    private LabelControl lblSriCode;
    private TextEdit txtSriCode;
    private LabelControl lblPercent;
    private SpinEdit spnPercent;
    private LabelControl lblDescription;
    private MemoEdit memDescription;
    private CheckEdit chkAppliesIva;
    private CheckEdit chkAppliesIncome;
    private CheckEdit chkIsActive;
    private SimpleButton btnCancel;
    private SimpleButton btnSave;
}
