namespace NuanSystem.WinForms.Services.Security.Users.Models;

public sealed record UserAdminItem(
    int Id,
    string UserName,
    string? Email,
    string? PhoneNumber,
    bool EmailConfirmed,
    bool PhoneNumberConfirmed,
    string? FirstName,
    string? LastName,
    string DisplayName,
    bool IsActive,
    bool IsLocked,
    bool CanUseWeb,
    bool CanUseMobile,
    int FailedAccessCount,
    DateTime? LastLoginAt,
    bool MustChangePassword,
    DateTime? LockoutEndAt,
    bool TwoFactorEnabled,
    string? ProfileImageUrl,
    byte[]? ProfileImage,
    string? ProfileImageContentType,
    string? ProfileImageFileName,
    int? RoleId,
    IReadOnlyCollection<string> Roles,
    IReadOnlyCollection<string> Companies,
    int? CreatedByUserId,
    string? CreatedByUserName,
    DateTime CreatedAt,
    int? UpdatedByUserId,
    string? UpdatedByUserName,
    DateTime? UpdatedAt,
    int? DeletedByUserId,
    string? DeletedByUserName,
    DateTime? DeletedAt);

