<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NuanSystem.WinForms.ViewModels\NuanSystem.WinForms.ViewModels.csproj" />
    <ProjectReference Include="..\NuanSystem.WinForms.Controls\NuanSystem.WinForms.Controls.csproj" />
    <ProjectReference Include="..\..\Backend\NuanSystem.Shared\NuanSystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Brand\*.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Icons\**\*.svg" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\KPI\*.svg" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Tabs\*.svg" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SyncSRI\SriTxtImports\SriTxtImportFilterDialog.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="SyncSRI\SriTxtImports\SriTxtImportForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Definitions\Inventory\ItemCommercialSegments\ItemCommercialSegmentsForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Definitions\Inventory\ItemCommercialSegments\ItemCommercialSegmentEditForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Definitions\Inventory\ItemCommercialSegments\ItemCommercialSegmentEditForm.Designer.cs">
      <DependentUpon>ItemCommercialSegmentEditForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Definitions\Inventory\ItemCommercialSegments\ItemCommercialSegmentsForm.resx">
      <DependentUpon>ItemCommercialSegmentsForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Definitions\Inventory\ItemCommercialSegments\ItemCommercialSegmentEditForm.resx">
      <DependentUpon>ItemCommercialSegmentEditForm.cs</DependentUpon>
    </EmbeddedResource>
    <Compile Update="Definitions\Inventory\ItemAlertTypes\ItemAlertTypesForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Definitions\Inventory\ItemAlertTypes\ItemAlertTypeEditForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Definitions\Inventory\ItemAlertTypes\ItemAlertTypeEditForm.Designer.cs">
      <DependentUpon>ItemAlertTypeEditForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Definitions\Inventory\ItemAlertTypes\ItemAlertTypesForm.resx">
      <DependentUpon>ItemAlertTypesForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Definitions\Inventory\ItemAlertTypes\ItemAlertTypeEditForm.resx">
      <DependentUpon>ItemAlertTypeEditForm.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DevExpress.Data.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Data.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Drawing.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Drawing.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Utils.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Utils.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Utils.v25.2.UI">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Utils.v25.2.UI.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Images.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Images.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.XtraEditors.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.XtraEditors.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.XtraBars.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.XtraBars.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.XtraGrid.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.XtraGrid.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.XtraPrinting.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.XtraPrinting.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.XtraReports.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.XtraReports.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>


  <ItemGroup>
    <Analyzer Include="C:\Program Files\DevExpress 25.2\Components\Offline Packages\devexpress.data\25.2.6-pre-26075\analyzers\dotnet\DevExpress.Generator.dll" Visible="false" Condition="Exists('C:\Program Files\DevExpress 25.2\Components\Offline Packages\devexpress.data\25.2.6-pre-26075\analyzers\dotnet\DevExpress.Generator.dll')" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="DevExpress.Win" Version="25.2.6" />
  </ItemGroup>
</Project>
