using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraTab;
using NuanSystem.WinForms.Controls.Buttons;

namespace NuanSystem.WinForms.Forms.Sync.Configuration;

partial class SyncProfileDistributionDialog
{
    private System.ComponentModel.IContainer components = null;
    private LabelControl lblTitle;
    private LabelControl lblSubtitle;
    private SeparatorControl sepTitle;
    private LabelControl lblEntityCode;
    private TextEdit txtEntityCode;
    private LabelControl lblEntityName;
    private TextEdit txtEntityName;
    private LabelControl lblBranchCompanyCode;
    private TextEdit txtBranchCompanyCode;
    private LabelControl lblBranchName;
    private TextEdit txtBranchName;
    private LabelControl lblIsEnabled;
    private ToggleSwitch swIsEnabled;
    private LabelControl lblBatchSize;
    private SpinEdit sedBatchSize;
    private LabelControl lblEffectiveBatch;
    private TextEdit txtEffectiveBatch;
    private LabelControl lblDistributionMode;
    private ComboBoxEdit cboDistributionMode;
    private LabelControl lblNoMatch;
    private TextEdit txtNoMatch;
    private XtraTabControl tabPolicy;
    private XtraTabPage pageSelected;
    private ButtonEdit txtCandidateSearch;
    private LabelControl lblSelectionStatus;
    private GridControl grcCandidates;
    private GridView grvCandidates;
    private GridColumn colCandidateSelected;
    private GridColumn colCandidateCode;
    private GridColumn colCandidateName;
    private GridColumn colCandidateActive;
    private RepositoryItemCheckEdit repCandidateSelected;
    private XtraTabPage pageRule;
    private LabelControl lblRuleMatch;
    private ComboBoxEdit cboRuleMatch;
    private SimpleButton btnAddRule;
    private SimpleButton btnRemoveRule;
    private GridControl grcRuleConditions;
    private GridView grvRuleConditions;
    private GridColumn colRuleField;
    private GridColumn colRuleOperator;
    private GridColumn colRuleValue;
    private RepositoryItemComboBox repRuleField;
    private RepositoryItemComboBox repRuleOperator;
    private LabelControl lblRuleHelp;
    private SeparatorControl sepFooter;
    private NuanActionButton btnSave;
    private NuanActionButton btnCancel;

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        lblTitle = new LabelControl();
        lblSubtitle = new LabelControl();
        sepTitle = new SeparatorControl();
        lblEntityCode = new LabelControl();
        txtEntityCode = new TextEdit();
        lblEntityName = new LabelControl();
        txtEntityName = new TextEdit();
        lblBranchCompanyCode = new LabelControl();
        txtBranchCompanyCode = new TextEdit();
        lblBranchName = new LabelControl();
        txtBranchName = new TextEdit();
        lblIsEnabled = new LabelControl();
        swIsEnabled = new ToggleSwitch();
        lblBatchSize = new LabelControl();
        sedBatchSize = new SpinEdit();
        lblEffectiveBatch = new LabelControl();
        txtEffectiveBatch = new TextEdit();
        lblDistributionMode = new LabelControl();
        cboDistributionMode = new ComboBoxEdit();
        lblNoMatch = new LabelControl();
        txtNoMatch = new TextEdit();
        tabPolicy = new XtraTabControl();
        pageSelected = new XtraTabPage();
        txtCandidateSearch = new ButtonEdit();
        lblSelectionStatus = new LabelControl();
        grcCandidates = new GridControl();
        grvCandidates = new GridView();
        colCandidateSelected = new GridColumn();
        colCandidateCode = new GridColumn();
        colCandidateName = new GridColumn();
        colCandidateActive = new GridColumn();
        repCandidateSelected = new RepositoryItemCheckEdit();
        pageRule = new XtraTabPage();
        lblRuleMatch = new LabelControl();
        cboRuleMatch = new ComboBoxEdit();
        btnAddRule = new SimpleButton();
        btnRemoveRule = new SimpleButton();
        grcRuleConditions = new GridControl();
        grvRuleConditions = new GridView();
        colRuleField = new GridColumn();
        colRuleOperator = new GridColumn();
        colRuleValue = new GridColumn();
        repRuleField = new RepositoryItemComboBox();
        repRuleOperator = new RepositoryItemComboBox();
        lblRuleHelp = new LabelControl();
        sepFooter = new SeparatorControl();
        btnSave = new NuanActionButton();
        btnCancel = new NuanActionButton();
        ((System.ComponentModel.ISupportInitialize)sepTitle).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtEntityCode.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtEntityName.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtBranchCompanyCode.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtBranchName.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)swIsEnabled.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)sedBatchSize.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtEffectiveBatch.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)cboDistributionMode.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtNoMatch.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tabPolicy).BeginInit();
        tabPolicy.SuspendLayout();
        pageSelected.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)txtCandidateSearch.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)grcCandidates).BeginInit();
        ((System.ComponentModel.ISupportInitialize)grvCandidates).BeginInit();
        ((System.ComponentModel.ISupportInitialize)repCandidateSelected).BeginInit();
        pageRule.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)cboRuleMatch.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)grcRuleConditions).BeginInit();
        ((System.ComponentModel.ISupportInitialize)grvRuleConditions).BeginInit();
        ((System.ComponentModel.ISupportInitialize)repRuleField).BeginInit();
        ((System.ComponentModel.ISupportInitialize)repRuleOperator).BeginInit();
        ((System.ComponentModel.ISupportInitialize)sepFooter).BeginInit();
        SuspendLayout();
        // 
        // lblTitle
        // 
        lblTitle.Appearance.Font = new Font("Segoe UI Semibold", 14F, FontStyle.Bold);
        lblTitle.Appearance.ForeColor = Color.FromArgb(0, 137, 111);
        lblTitle.Appearance.Options.UseFont = true;
        lblTitle.Appearance.Options.UseForeColor = true;
        lblTitle.Location = new Point(24, 16);
        lblTitle.Name = "lblTitle";
        lblTitle.Size = new Size(221, 25);
        lblTitle.TabIndex = 0;
        lblTitle.Text = "Configurar distribución";
        // 
        // lblSubtitle
        // 
        lblSubtitle.Appearance.Font = new Font("Segoe UI", 9F);
        lblSubtitle.Appearance.ForeColor = Color.FromArgb(100, 112, 132);
        lblSubtitle.Appearance.Options.UseFont = true;
        lblSubtitle.Appearance.Options.UseForeColor = true;
        lblSubtitle.Location = new Point(24, 46);
        lblSubtitle.Name = "lblSubtitle";
        lblSubtitle.Size = new Size(491, 15);
        lblSubtitle.TabIndex = 1;
        lblSubtitle.Text = "Defina qué registros recibe la sucursal sin editar JSON técnico manualmente.";
        // 
        // sepTitle
        // 
        sepTitle.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        sepTitle.LineColor = Color.FromArgb(0, 184, 148);
        sepTitle.Location = new Point(24, 65);
        sepTitle.Name = "sepTitle";
        sepTitle.Size = new Size(732, 12);
        sepTitle.TabIndex = 2;
        // 
        // summary controls
        // 
        lblEntityCode.Location = new Point(24, 88);
        lblEntityCode.Name = "lblEntityCode";
        lblEntityCode.Size = new Size(84, 15);
        lblEntityCode.Text = "Código entidad";
        txtEntityCode.Location = new Point(150, 84);
        txtEntityCode.Name = "txtEntityCode";
        txtEntityCode.Properties.ReadOnly = true;
        txtEntityCode.Size = new Size(220, 22);
        lblEntityName.Location = new Point(390, 88);
        lblEntityName.Name = "lblEntityName";
        lblEntityName.Size = new Size(89, 15);
        lblEntityName.Text = "Nombre entidad";
        txtEntityName.Location = new Point(516, 84);
        txtEntityName.Name = "txtEntityName";
        txtEntityName.Properties.ReadOnly = true;
        txtEntityName.Size = new Size(240, 22);
        lblBranchCompanyCode.Location = new Point(24, 120);
        lblBranchCompanyCode.Name = "lblBranchCompanyCode";
        lblBranchCompanyCode.Size = new Size(102, 15);
        lblBranchCompanyCode.Text = "Empresa sucursal";
        txtBranchCompanyCode.Location = new Point(150, 116);
        txtBranchCompanyCode.Name = "txtBranchCompanyCode";
        txtBranchCompanyCode.Properties.ReadOnly = true;
        txtBranchCompanyCode.Size = new Size(220, 22);
        lblBranchName.Location = new Point(390, 120);
        lblBranchName.Name = "lblBranchName";
        lblBranchName.Size = new Size(90, 15);
        lblBranchName.Text = "Nombre sucursal";
        txtBranchName.Location = new Point(516, 116);
        txtBranchName.Name = "txtBranchName";
        txtBranchName.Properties.ReadOnly = true;
        txtBranchName.Size = new Size(240, 22);
        lblIsEnabled.Location = new Point(24, 152);
        lblIsEnabled.Name = "lblIsEnabled";
        lblIsEnabled.Size = new Size(54, 15);
        lblIsEnabled.Text = "Habilitado";
        swIsEnabled.EditValue = true;
        swIsEnabled.Location = new Point(150, 148);
        swIsEnabled.Name = "swIsEnabled";
        swIsEnabled.Properties.OffText = "No";
        swIsEnabled.Properties.OnText = "Sí";
        swIsEnabled.Size = new Size(90, 20);
        lblBatchSize.Location = new Point(260, 152);
        lblBatchSize.Name = "lblBatchSize";
        lblBatchSize.Size = new Size(82, 15);
        lblBatchSize.Text = "Batch específico";
        sedBatchSize.Location = new Point(360, 148);
        sedBatchSize.Name = "sedBatchSize";
        sedBatchSize.Properties.AllowNullInput = DefaultBoolean.True;
        sedBatchSize.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
        sedBatchSize.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo), new EditorButton(ButtonPredefines.Delete) });
        sedBatchSize.Properties.IsFloatValue = false;
        sedBatchSize.Properties.MaxValue = 10000;
        sedBatchSize.Properties.MinValue = 1;
        sedBatchSize.Size = new Size(130, 22);
        lblEffectiveBatch.Location = new Point(510, 152);
        lblEffectiveBatch.Name = "lblEffectiveBatch";
        lblEffectiveBatch.Size = new Size(72, 15);
        lblEffectiveBatch.Text = "Batch efectivo";
        txtEffectiveBatch.Location = new Point(606, 148);
        txtEffectiveBatch.Name = "txtEffectiveBatch";
        txtEffectiveBatch.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
        txtEffectiveBatch.Properties.ReadOnly = true;
        txtEffectiveBatch.Size = new Size(150, 22);
        lblDistributionMode.Location = new Point(24, 184);
        lblDistributionMode.Name = "lblDistributionMode";
        lblDistributionMode.Size = new Size(113, 15);
        lblDistributionMode.Text = "Modalidad de envío";
        cboDistributionMode.Location = new Point(150, 180);
        cboDistributionMode.Name = "cboDistributionMode";
        cboDistributionMode.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        cboDistributionMode.Size = new Size(220, 22);
        lblNoMatch.Location = new Point(390, 184);
        lblNoMatch.Name = "lblNoMatch";
        lblNoMatch.Size = new Size(109, 15);
        lblNoMatch.Text = "Si no hay coincidencia";
        txtNoMatch.EditValue = "Conservar solamente en Master";
        txtNoMatch.Location = new Point(516, 180);
        txtNoMatch.Name = "txtNoMatch";
        txtNoMatch.Properties.ReadOnly = true;
        txtNoMatch.Size = new Size(240, 22);
        // 
        // tabPolicy
        // 
        tabPolicy.Location = new Point(24, 216);
        tabPolicy.Name = "tabPolicy";
        tabPolicy.SelectedTabPage = pageSelected;
        tabPolicy.Size = new Size(732, 390);
        tabPolicy.TabPages.AddRange(new XtraTabPage[] { pageSelected, pageRule });
        // 
        // pageSelected
        // 
        pageSelected.Controls.Add(txtCandidateSearch);
        pageSelected.Controls.Add(lblSelectionStatus);
        pageSelected.Controls.Add(grcCandidates);
        pageSelected.Name = "pageSelected";
        pageSelected.Size = new Size(730, 365);
        pageSelected.Text = "Registros seleccionados";
        txtCandidateSearch.Location = new Point(14, 14);
        txtCandidateSearch.Name = "txtCandidateSearch";
        txtCandidateSearch.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Search) });
        txtCandidateSearch.Properties.NullValuePrompt = "Buscar por código o nombre";
        txtCandidateSearch.Size = new Size(470, 22);
        lblSelectionStatus.Appearance.ForeColor = Color.FromArgb(100, 112, 132);
        lblSelectionStatus.Appearance.Options.UseForeColor = true;
        lblSelectionStatus.Location = new Point(506, 18);
        lblSelectionStatus.Name = "lblSelectionStatus";
        lblSelectionStatus.Size = new Size(132, 15);
        lblSelectionStatus.Text = "0 registros seleccionados";
        grcCandidates.Location = new Point(14, 47);
        grcCandidates.MainView = grvCandidates;
        grcCandidates.Name = "grcCandidates";
        grcCandidates.RepositoryItems.AddRange(new RepositoryItem[] { repCandidateSelected });
        grcCandidates.Size = new Size(700, 302);
        grcCandidates.ViewCollection.AddRange(new BaseView[] { grvCandidates });
        grvCandidates.Columns.AddRange(new GridColumn[] { colCandidateSelected, colCandidateCode, colCandidateName, colCandidateActive });
        grvCandidates.GridControl = grcCandidates;
        grvCandidates.Name = "grvCandidates";
        grvCandidates.OptionsView.ShowGroupPanel = false;
        grvCandidates.OptionsView.ShowIndicator = false;
        colCandidateSelected.Caption = "Enviar";
        colCandidateSelected.ColumnEdit = repCandidateSelected;
        colCandidateSelected.FieldName = "IsSelected";
        colCandidateSelected.Name = "colCandidateSelected";
        colCandidateSelected.Visible = true;
        colCandidateSelected.VisibleIndex = 0;
        colCandidateSelected.Width = 60;
        colCandidateCode.Caption = "Código";
        colCandidateCode.FieldName = "EntityCode";
        colCandidateCode.Name = "colCandidateCode";
        colCandidateCode.OptionsColumn.AllowEdit = false;
        colCandidateCode.Visible = true;
        colCandidateCode.VisibleIndex = 1;
        colCandidateCode.Width = 180;
        colCandidateName.Caption = "Nombre";
        colCandidateName.FieldName = "EntityName";
        colCandidateName.Name = "colCandidateName";
        colCandidateName.OptionsColumn.AllowEdit = false;
        colCandidateName.Visible = true;
        colCandidateName.VisibleIndex = 2;
        colCandidateName.Width = 380;
        colCandidateActive.Caption = "Activo";
        colCandidateActive.FieldName = "IsActive";
        colCandidateActive.Name = "colCandidateActive";
        colCandidateActive.OptionsColumn.AllowEdit = false;
        colCandidateActive.Visible = true;
        colCandidateActive.VisibleIndex = 3;
        colCandidateActive.Width = 70;
        // 
        // pageRule
        // 
        pageRule.Controls.Add(lblRuleMatch);
        pageRule.Controls.Add(cboRuleMatch);
        pageRule.Controls.Add(btnAddRule);
        pageRule.Controls.Add(btnRemoveRule);
        pageRule.Controls.Add(grcRuleConditions);
        pageRule.Controls.Add(lblRuleHelp);
        pageRule.Name = "pageRule";
        pageRule.Size = new Size(730, 365);
        pageRule.Text = "Editor visual de regla";
        lblRuleMatch.Location = new Point(14, 18);
        lblRuleMatch.Name = "lblRuleMatch";
        lblRuleMatch.Size = new Size(91, 15);
        lblRuleMatch.Text = "Coincidencia de";
        cboRuleMatch.Location = new Point(118, 14);
        cboRuleMatch.Name = "cboRuleMatch";
        cboRuleMatch.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        cboRuleMatch.Size = new Size(130, 22);
        btnAddRule.Location = new Point(504, 12);
        btnAddRule.Name = "btnAddRule";
        btnAddRule.Size = new Size(100, 26);
        btnAddRule.Text = "Agregar";
        btnRemoveRule.Location = new Point(610, 12);
        btnRemoveRule.Name = "btnRemoveRule";
        btnRemoveRule.Size = new Size(100, 26);
        btnRemoveRule.Text = "Quitar";
        grcRuleConditions.Location = new Point(14, 47);
        grcRuleConditions.MainView = grvRuleConditions;
        grcRuleConditions.Name = "grcRuleConditions";
        grcRuleConditions.RepositoryItems.AddRange(new RepositoryItem[] { repRuleField, repRuleOperator });
        grcRuleConditions.Size = new Size(700, 262);
        grcRuleConditions.ViewCollection.AddRange(new BaseView[] { grvRuleConditions });
        grvRuleConditions.Columns.AddRange(new GridColumn[] { colRuleField, colRuleOperator, colRuleValue });
        grvRuleConditions.GridControl = grcRuleConditions;
        grvRuleConditions.Name = "grvRuleConditions";
        grvRuleConditions.OptionsView.NewItemRowPosition = NewItemRowPosition.Bottom;
        grvRuleConditions.OptionsView.ShowGroupPanel = false;
        grvRuleConditions.OptionsView.ShowIndicator = false;
        colRuleField.Caption = "Campo";
        colRuleField.ColumnEdit = repRuleField;
        colRuleField.FieldName = "Field";
        colRuleField.Name = "colRuleField";
        colRuleField.Visible = true;
        colRuleField.VisibleIndex = 0;
        colRuleField.Width = 210;
        colRuleOperator.Caption = "Operador";
        colRuleOperator.ColumnEdit = repRuleOperator;
        colRuleOperator.FieldName = "Operator";
        colRuleOperator.Name = "colRuleOperator";
        colRuleOperator.Visible = true;
        colRuleOperator.VisibleIndex = 1;
        colRuleOperator.Width = 180;
        colRuleValue.Caption = "Valor (separe listas con coma)";
        colRuleValue.FieldName = "Value";
        colRuleValue.Name = "colRuleValue";
        colRuleValue.Visible = true;
        colRuleValue.VisibleIndex = 2;
        colRuleValue.Width = 300;
        repRuleField.AutoHeight = false;
        repRuleField.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        repRuleField.TextEditStyle = TextEditStyles.DisableTextEditor;
        repRuleOperator.AutoHeight = false;
        repRuleOperator.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        repRuleOperator.TextEditStyle = TextEditStyles.DisableTextEditor;
        lblRuleHelp.Appearance.ForeColor = Color.FromArgb(100, 112, 132);
        lblRuleHelp.Appearance.Options.UseForeColor = true;
        lblRuleHelp.Location = new Point(14, 323);
        lblRuleHelp.Name = "lblRuleHelp";
        lblRuleHelp.Size = new Size(619, 15);
        lblRuleHelp.Text = "All exige que coincidan todas las condiciones; Any acepta que coincida al menos una.";
        // 
        // footer
        // 
        sepFooter.Anchor = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        sepFooter.LineColor = Color.FromArgb(226, 232, 240);
        sepFooter.Location = new Point(0, 616);
        sepFooter.Name = "sepFooter";
        sepFooter.Size = new Size(780, 12);
        btnSave.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
        btnSave.Appearance.BackColor = Color.FromArgb(0, 184, 148);
        btnSave.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        btnSave.Appearance.ForeColor = Color.White;
        btnSave.Appearance.Options.UseBackColor = true;
        btnSave.Appearance.Options.UseFont = true;
        btnSave.Appearance.Options.UseForeColor = true;
        btnSave.ButtonKind = NuanActionButtonKind.Save;
        btnSave.ButtonText = "Guardar";
        btnSave.Location = new Point(556, 634);
        btnSave.Name = "btnSave";
        btnSave.Size = new Size(100, 36);
        btnSave.Text = "Guardar";
        btnCancel.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
        btnCancel.Appearance.BackColor = Color.FromArgb(99, 110, 114);
        btnCancel.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        btnCancel.Appearance.ForeColor = Color.White;
        btnCancel.Appearance.Options.UseBackColor = true;
        btnCancel.Appearance.Options.UseFont = true;
        btnCancel.Appearance.Options.UseForeColor = true;
        btnCancel.ButtonKind = NuanActionButtonKind.Cancel;
        btnCancel.ButtonText = "Cancelar";
        btnCancel.DialogResult = DialogResult.Cancel;
        btnCancel.Location = new Point(662, 634);
        btnCancel.Name = "btnCancel";
        btnCancel.Size = new Size(100, 36);
        btnCancel.Text = "Cancelar";
        // 
        // SyncProfileDistributionDialog
        // 
        AcceptButton = btnSave;
        Appearance.Options.UseFont = true;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        CancelButton = btnCancel;
        ClientSize = new Size(780, 684);
        Controls.Add(lblTitle);
        Controls.Add(lblSubtitle);
        Controls.Add(sepTitle);
        Controls.Add(lblEntityCode);
        Controls.Add(txtEntityCode);
        Controls.Add(lblEntityName);
        Controls.Add(txtEntityName);
        Controls.Add(lblBranchCompanyCode);
        Controls.Add(txtBranchCompanyCode);
        Controls.Add(lblBranchName);
        Controls.Add(txtBranchName);
        Controls.Add(lblIsEnabled);
        Controls.Add(swIsEnabled);
        Controls.Add(lblBatchSize);
        Controls.Add(sedBatchSize);
        Controls.Add(lblEffectiveBatch);
        Controls.Add(txtEffectiveBatch);
        Controls.Add(lblDistributionMode);
        Controls.Add(cboDistributionMode);
        Controls.Add(lblNoMatch);
        Controls.Add(txtNoMatch);
        Controls.Add(tabPolicy);
        Controls.Add(sepFooter);
        Controls.Add(btnSave);
        Controls.Add(btnCancel);
        Font = new Font("Segoe UI", 9F);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "SyncProfileDistributionDialog";
        ShowInTaskbar = false;
        StartPosition = FormStartPosition.CenterParent;
        Text = "Configurar distribución";
        ((System.ComponentModel.ISupportInitialize)sepTitle).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtEntityCode.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtEntityName.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtBranchCompanyCode.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtBranchName.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)swIsEnabled.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)sedBatchSize.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtEffectiveBatch.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)cboDistributionMode.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtNoMatch.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tabPolicy).EndInit();
        tabPolicy.ResumeLayout(false);
        pageSelected.ResumeLayout(false);
        pageSelected.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)txtCandidateSearch.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)grcCandidates).EndInit();
        ((System.ComponentModel.ISupportInitialize)grvCandidates).EndInit();
        ((System.ComponentModel.ISupportInitialize)repCandidateSelected).EndInit();
        pageRule.ResumeLayout(false);
        pageRule.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)cboRuleMatch.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)grcRuleConditions).EndInit();
        ((System.ComponentModel.ISupportInitialize)grvRuleConditions).EndInit();
        ((System.ComponentModel.ISupportInitialize)repRuleField).EndInit();
        ((System.ComponentModel.ISupportInitialize)repRuleOperator).EndInit();
        ((System.ComponentModel.ISupportInitialize)sepFooter).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }
}
