using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using NuanSystem.WinForms.Controls.Buttons;
using NuanSystem.WinForms.Forms.Common;

namespace NuanSystem.WinForms.Forms.SriDocuments;

partial class SriDocumentMonitorFilterDialog
{
    private System.ComponentModel.IContainer components=null!;
    private LabelControl lblDateFrom=null!;
    private DateEdit dateFrom=null!;
    private LabelControl lblDateTo=null!;
    private DateEdit dateTo=null!;
    private LabelControl lblEnvironment=null!;
    private ComboBoxEdit cmbEnvironment=null!;
    private LabelControl lblStatus=null!;
    private ComboBoxEdit cmbStatus=null!;
    private LabelControl lblDocumentType=null!;
    private ComboBoxEdit cmbDocumentType=null!;
    private LabelControl lblSourceType=null!;
    private ComboBoxEdit cmbSourceType=null!;
    private LabelControl lblSearch=null!;
    private TextEdit txtSearch=null!;
    private NuanActionButton btnApply=null!;
    private NuanActionButton btnClear=null!;
    private NuanActionButton btnCancel=null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components=new System.ComponentModel.Container();
        lblDateFrom=new LabelControl();
        dateFrom=new DateEdit();
        lblDateTo=new LabelControl();
        dateTo=new DateEdit();
        lblEnvironment=new LabelControl();
        cmbEnvironment=new ComboBoxEdit();
        lblStatus=new LabelControl();
        cmbStatus=new ComboBoxEdit();
        lblDocumentType=new LabelControl();
        cmbDocumentType=new ComboBoxEdit();
        lblSourceType=new LabelControl();
        cmbSourceType=new ComboBoxEdit();
        lblSearch=new LabelControl();
        txtSearch=new TextEdit();
        btnApply=new NuanActionButton();
        btnClear=new NuanActionButton();
        btnCancel=new NuanActionButton();
        ((System.ComponentModel.ISupportInitialize)dateFrom.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dateFrom.Properties.CalendarTimeProperties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dateTo.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dateTo.Properties.CalendarTimeProperties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)cmbEnvironment.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)cmbStatus.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)cmbDocumentType.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)cmbSourceType.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtSearch.Properties).BeginInit();
        SuspendLayout();
        lblDateFrom.Appearance.Font=AppTypography.LabelFont;
        lblDateFrom.Appearance.Options.UseFont=true;
        lblDateFrom.Location=new Point(16,17);
        lblDateFrom.Name="lblDateFrom";
        lblDateFrom.Size=new Size(62,15);
        lblDateFrom.TabIndex=0;
        lblDateFrom.Text="Fecha desde";
        dateFrom.EditValue=null;
        dateFrom.Location=new Point(142,14);
        dateFrom.Name="dateFrom";
        dateFrom.Properties.Appearance.Font=AppTypography.InputFont;
        dateFrom.Properties.Appearance.Options.UseFont=true;
        dateFrom.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        dateFrom.Properties.CalendarTimeProperties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        dateFrom.Properties.NullText="Todas";
        dateFrom.Size=new Size(264,22);
        dateFrom.TabIndex=1;
        lblDateTo.Appearance.Font=AppTypography.LabelFont;
        lblDateTo.Appearance.Options.UseFont=true;
        lblDateTo.Location=new Point(16,45);
        lblDateTo.Name="lblDateTo";
        lblDateTo.Size=new Size(59,15);
        lblDateTo.TabIndex=2;
        lblDateTo.Text="Fecha hasta";
        dateTo.EditValue=null;
        dateTo.Location=new Point(142,42);
        dateTo.Name="dateTo";
        dateTo.Properties.Appearance.Font=AppTypography.InputFont;
        dateTo.Properties.Appearance.Options.UseFont=true;
        dateTo.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        dateTo.Properties.CalendarTimeProperties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        dateTo.Properties.NullText="Todas";
        dateTo.Size=new Size(264,22);
        dateTo.TabIndex=3;
        lblEnvironment.Appearance.Font=AppTypography.LabelFont;
        lblEnvironment.Appearance.Options.UseFont=true;
        lblEnvironment.Location=new Point(16,73);
        lblEnvironment.Name="lblEnvironment";
        lblEnvironment.Size=new Size(49,15);
        lblEnvironment.TabIndex=4;
        lblEnvironment.Text="Ambiente";
        cmbEnvironment.Location=new Point(142,70);
        cmbEnvironment.Name="cmbEnvironment";
        cmbEnvironment.Properties.Appearance.Font=AppTypography.InputFont;
        cmbEnvironment.Properties.Appearance.Options.UseFont=true;
        cmbEnvironment.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        cmbEnvironment.Properties.Items.AddRange(new object[] { "Todos","Pruebas","Producción" });
        cmbEnvironment.Properties.TextEditStyle=TextEditStyles.DisableTextEditor;
        cmbEnvironment.SelectedIndex=0;
        cmbEnvironment.Size=new Size(264,22);
        cmbEnvironment.TabIndex=5;
        lblStatus.Appearance.Font=AppTypography.LabelFont;
        lblStatus.Appearance.Options.UseFont=true;
        lblStatus.Location=new Point(16,101);
        lblStatus.Name="lblStatus";
        lblStatus.Size=new Size(35,15);
        lblStatus.TabIndex=6;
        lblStatus.Text="Estado";
        cmbStatus.Location=new Point(142,98);
        cmbStatus.Name="cmbStatus";
        cmbStatus.Properties.Appearance.Font=AppTypography.InputFont;
        cmbStatus.Properties.Appearance.Options.UseFont=true;
        cmbStatus.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        cmbStatus.Properties.Items.AddRange(new object[] { "Todos","Preparado","Pendiente","Consultando","Reintento programado","Autorizado","No encontrado","Fallido","DeadLetter","Cancelado" });
        cmbStatus.Properties.TextEditStyle=TextEditStyles.DisableTextEditor;
        cmbStatus.SelectedIndex=0;
        cmbStatus.Size=new Size(264,22);
        cmbStatus.TabIndex=7;
        lblDocumentType.Appearance.Font=AppTypography.LabelFont;
        lblDocumentType.Appearance.Options.UseFont=true;
        lblDocumentType.Location=new Point(16,129);
        lblDocumentType.Name="lblDocumentType";
        lblDocumentType.Size=new Size(84,15);
        lblDocumentType.TabIndex=8;
        lblDocumentType.Text="Tipo documento";
        cmbDocumentType.Location=new Point(142,126);
        cmbDocumentType.Name="cmbDocumentType";
        cmbDocumentType.Properties.Appearance.Font=AppTypography.InputFont;
        cmbDocumentType.Properties.Appearance.Options.UseFont=true;
        cmbDocumentType.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        cmbDocumentType.Properties.Items.AddRange(new object[] { "Todos","Factura (01)","Nota de crédito (04)","Retención (07)" });
        cmbDocumentType.Properties.TextEditStyle=TextEditStyles.DisableTextEditor;
        cmbDocumentType.SelectedIndex=0;
        cmbDocumentType.Size=new Size(264,22);
        cmbDocumentType.TabIndex=9;
        lblSourceType.Appearance.Font=AppTypography.LabelFont;
        lblSourceType.Appearance.Options.UseFont=true;
        lblSourceType.Location=new Point(16,157);
        lblSourceType.Name="lblSourceType";
        lblSourceType.Size=new Size(36,15);
        lblSourceType.TabIndex=10;
        lblSourceType.Text="Origen";
        cmbSourceType.Location=new Point(142,154);
        cmbSourceType.Name="cmbSourceType";
        cmbSourceType.Properties.Appearance.Font=AppTypography.InputFont;
        cmbSourceType.Properties.Appearance.Options.UseFont=true;
        cmbSourceType.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        cmbSourceType.Properties.Items.AddRange(new object[] { "Todos","NuanSystem","TXT SRI","SAP Add-On","Manual","API externa" });
        cmbSourceType.Properties.TextEditStyle=TextEditStyles.DisableTextEditor;
        cmbSourceType.SelectedIndex=0;
        cmbSourceType.Size=new Size(264,22);
        cmbSourceType.TabIndex=11;
        lblSearch.Appearance.Font=AppTypography.LabelFont;
        lblSearch.Appearance.Options.UseFont=true;
        lblSearch.Location=new Point(16,185);
        lblSearch.Name="lblSearch";
        lblSearch.Size=new Size(99,15);
        lblSearch.TabIndex=12;
        lblSearch.Text="Referencia segura";
        txtSearch.Location=new Point(142,182);
        txtSearch.Name="txtSearch";
        txtSearch.Properties.Appearance.Font=AppTypography.InputFont;
        txtSearch.Properties.Appearance.Options.UseFont=true;
        txtSearch.Properties.MaxLength=200;
        txtSearch.Properties.NullValuePrompt="Contiene...";
        txtSearch.Size=new Size(264,22);
        txtSearch.TabIndex=13;
        btnApply.ButtonKind=NuanActionButtonKind.Save;
        btnApply.ButtonText="Aplicar";
        btnApply.Location=new Point(318,222);
        btnApply.Name="btnApply";
        btnApply.Size=new Size(88,34);
        btnApply.TabIndex=14;
        btnApply.Text="Aplicar";
        btnApply.Click+=ApplyButton_Click;
        btnClear.ButtonKind=NuanActionButtonKind.Cancel;
        btnClear.ButtonText="Limpiar";
        btnClear.Location=new Point(224,222);
        btnClear.Name="btnClear";
        btnClear.Size=new Size(88,34);
        btnClear.TabIndex=15;
        btnClear.Text="Limpiar";
        btnClear.Click+=ClearButton_Click;
        btnCancel.ButtonKind=NuanActionButtonKind.Cancel;
        btnCancel.ButtonText="Cancelar";
        btnCancel.DialogResult=DialogResult.Cancel;
        btnCancel.Location=new Point(130,222);
        btnCancel.Name="btnCancel";
        btnCancel.Size=new Size(88,34);
        btnCancel.TabIndex=16;
        btnCancel.Text="Cancelar";
        AcceptButton=btnApply;
        AutoScaleDimensions=new SizeF(7F,15F);
        AutoScaleMode=AutoScaleMode.Font;
        CancelButton=btnCancel;
        ClientSize=new Size(422,270);
        Controls.Add(btnCancel);
        Controls.Add(btnClear);
        Controls.Add(btnApply);
        Controls.Add(txtSearch);
        Controls.Add(lblSearch);
        Controls.Add(cmbSourceType);
        Controls.Add(lblSourceType);
        Controls.Add(cmbDocumentType);
        Controls.Add(lblDocumentType);
        Controls.Add(cmbStatus);
        Controls.Add(lblStatus);
        Controls.Add(cmbEnvironment);
        Controls.Add(lblEnvironment);
        Controls.Add(dateTo);
        Controls.Add(lblDateTo);
        Controls.Add(dateFrom);
        Controls.Add(lblDateFrom);
        Font=AppTypography.BaseFont;
        FormBorderStyle=FormBorderStyle.FixedDialog;
        MaximizeBox=false;
        MinimizeBox=false;
        Name="SriDocumentMonitorFilterDialog";
        StartPosition=FormStartPosition.CenterParent;
        Text="Filtros del Monitor SRI";
        ((System.ComponentModel.ISupportInitialize)dateFrom.Properties.CalendarTimeProperties).EndInit();
        ((System.ComponentModel.ISupportInitialize)dateFrom.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)dateTo.Properties.CalendarTimeProperties).EndInit();
        ((System.ComponentModel.ISupportInitialize)dateTo.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)cmbEnvironment.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)cmbStatus.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)cmbDocumentType.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)cmbSourceType.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtSearch.Properties).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }
}
