using DevExpress.XtraEditors;
using NuanSystem.WinForms.Controls.Buttons;

namespace NuanSystem.WinForms.Forms.Sap;

partial class SapSyncExecutionFilterDialog
{
    private System.ComponentModel.IContainer components = null; private LabelControl entityLabel; private LabelControl directionLabel; private LabelControl statusLabel; private LabelControl triggerLabel; private LabelControl fromLabel; private LabelControl toLabel; private TextEdit entityEdit; private ComboBoxEdit directionEdit; private ComboBoxEdit statusEdit; private ComboBoxEdit triggerEdit; private DateEdit fromEdit; private DateEdit toEdit; private NuanActionButton acceptButton; private NuanActionButton cancelActionButton;
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container(); entityLabel = new LabelControl(); directionLabel = new LabelControl(); statusLabel = new LabelControl(); triggerLabel = new LabelControl(); fromLabel = new LabelControl(); toLabel = new LabelControl(); entityEdit = new TextEdit(); directionEdit = new ComboBoxEdit(); statusEdit = new ComboBoxEdit(); triggerEdit = new ComboBoxEdit(); fromEdit = new DateEdit(); toEdit = new DateEdit(); acceptButton = new NuanActionButton(); cancelActionButton = new NuanActionButton(); ((System.ComponentModel.ISupportInitialize)entityEdit.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)directionEdit.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)statusEdit.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)triggerEdit.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)fromEdit.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)fromEdit.Properties.CalendarTimeProperties).BeginInit(); ((System.ComponentModel.ISupportInitialize)toEdit.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)toEdit.Properties.CalendarTimeProperties).BeginInit(); SuspendLayout();
        entityLabel.Location = new Point(20, 22); entityLabel.Name = "entityLabel"; entityLabel.Text = "Entidad"; entityEdit.Location = new Point(155, 19); entityEdit.Name = "entityEdit"; entityEdit.Size = new Size(250, 22); entityEdit.TabIndex = 0;
        directionLabel.Location = new Point(20, 60); directionLabel.Name = "directionLabel"; directionLabel.Text = "Direccion"; directionEdit.Location = new Point(155, 57); directionEdit.Name = "directionEdit"; directionEdit.Properties.Buttons.Add(new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)); directionEdit.Properties.Items.AddRange(new object[] { "Todos", "SapToErp", "ErpToSap" }); directionEdit.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor; directionEdit.SelectedIndex = 0; directionEdit.Size = new Size(250, 22); directionEdit.TabIndex = 1;
        statusLabel.Location = new Point(20, 98); statusLabel.Name = "statusLabel"; statusLabel.Text = "Estado"; statusEdit.Location = new Point(155, 95); statusEdit.Name = "statusEdit"; statusEdit.Properties.Buttons.Add(new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)); statusEdit.Properties.Items.AddRange(new object[] { "Todos", "Pending", "Running", "RetryScheduled", "Completed", "CompletedWithWarnings", "CompletedWithErrors", "Failed", "Cancelled" }); statusEdit.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor; statusEdit.SelectedIndex = 0; statusEdit.Size = new Size(250, 22); statusEdit.TabIndex = 2;
        triggerLabel.Location = new Point(20, 136); triggerLabel.Name = "triggerLabel"; triggerLabel.Text = "Origen"; triggerEdit.Location = new Point(155, 133); triggerEdit.Name = "triggerEdit"; triggerEdit.Properties.Buttons.Add(new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)); triggerEdit.Properties.Items.AddRange(new object[] { "Todos", "Manual", "Scheduled", "Retry" }); triggerEdit.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor; triggerEdit.SelectedIndex = 0; triggerEdit.Size = new Size(250, 22); triggerEdit.TabIndex = 3;
        fromLabel.Location = new Point(20, 174); fromLabel.Name = "fromLabel"; fromLabel.Text = "Desde"; fromEdit.Location = new Point(155, 171); fromEdit.Name = "fromEdit"; fromEdit.Properties.Buttons.Add(new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)); fromEdit.Size = new Size(160, 22); fromEdit.TabIndex = 4;
        toLabel.Location = new Point(20, 212); toLabel.Name = "toLabel"; toLabel.Text = "Hasta"; toEdit.Location = new Point(155, 209); toEdit.Name = "toEdit"; toEdit.Properties.Buttons.Add(new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)); toEdit.Size = new Size(160, 22); toEdit.TabIndex = 5;
        acceptButton.ButtonKind = NuanActionButtonKind.Search; acceptButton.ButtonText = "Aplicar"; acceptButton.Location = new Point(199, 257); acceptButton.Size = new Size(100, 36); acceptButton.TabIndex = 6; cancelActionButton.ButtonKind = NuanActionButtonKind.Cancel; cancelActionButton.ButtonText = "Cancelar"; cancelActionButton.DialogResult = DialogResult.Cancel; cancelActionButton.Location = new Point(305, 257); cancelActionButton.Size = new Size(100, 36); cancelActionButton.TabIndex = 7;
        AcceptButton = acceptButton; CancelButton = cancelActionButton; AutoScaleDimensions = new SizeF(7F, 15F); AutoScaleMode = AutoScaleMode.Font; ClientSize = new Size(430, 312); Controls.AddRange(new Control[] { entityLabel, entityEdit, directionLabel, directionEdit, statusLabel, statusEdit, triggerLabel, triggerEdit, fromLabel, fromEdit, toLabel, toEdit, acceptButton, cancelActionButton }); FormBorderStyle = FormBorderStyle.FixedDialog; MaximizeBox = false; MinimizeBox = false; Name = "SapSyncExecutionFilterDialog"; StartPosition = FormStartPosition.CenterParent; Text = "Filtrar ejecuciones SAP";
        ((System.ComponentModel.ISupportInitialize)entityEdit.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)directionEdit.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)statusEdit.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)triggerEdit.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)fromEdit.Properties.CalendarTimeProperties).EndInit(); ((System.ComponentModel.ISupportInitialize)fromEdit.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)toEdit.Properties.CalendarTimeProperties).EndInit(); ((System.ComponentModel.ISupportInitialize)toEdit.Properties).EndInit(); ResumeLayout(false); PerformLayout();
    }
    protected override void Dispose(bool disposing) { if (disposing) components?.Dispose(); base.Dispose(disposing); }
}
