using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraTab;

namespace NuanSystem.WinForms.Forms.Sap;

partial class SapSyncProfileEditForm
{
    private System.ComponentModel.IContainer components = null;
    private LabelControl companyLabel; private LookUpEdit companyEdit; private LabelControl codeLabel; private TextEdit codeEdit;
    private LabelControl nameLabel; private TextEdit nameEdit; private LabelControl descriptionLabel; private MemoEdit descriptionEdit; private LabelControl statusLabel;
    private XtraTabControl tabs; private XtraTabPage generalTab; private XtraTabPage entitiesTab; private GridControl entitiesGrid; private GridView entitiesView;
    private RepositoryItemComboBox directionRepository; private RepositoryItemComboBox modeRepository; private RepositoryItemComboBox scheduleRepository;
    private GridColumn entityCodeColumn; private GridColumn entityNameColumn; private GridColumn directionColumn; private GridColumn modeColumn; private GridColumn batchColumn;
    private GridColumn attemptsColumn; private GridColumn orderColumn; private GridColumn activeColumn; private GridColumn scheduleTypeColumn; private GridColumn intervalColumn;
    private GridColumn continueOnErrorColumn; private GridColumn timeoutColumn; private GridColumn executionTimeColumn; private GridColumn timeZoneColumn;
    private GridColumn preventConcurrentColumn; private GridColumn scheduleActiveColumn; private GridColumn nextExecutionColumn; private GridColumn lastExecutionColumn;

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        tabs = new XtraTabControl(); generalTab = new XtraTabPage(); entitiesTab = new XtraTabPage(); companyLabel = new LabelControl(); companyEdit = new LookUpEdit();
        codeLabel = new LabelControl(); codeEdit = new TextEdit(); nameLabel = new LabelControl(); nameEdit = new TextEdit(); descriptionLabel = new LabelControl(); descriptionEdit = new MemoEdit(); statusLabel = new LabelControl();
        entitiesGrid = new GridControl(); entitiesView = new GridView(); directionRepository = new RepositoryItemComboBox(); modeRepository = new RepositoryItemComboBox(); scheduleRepository = new RepositoryItemComboBox();
        entityCodeColumn = new GridColumn(); entityNameColumn = new GridColumn(); directionColumn = new GridColumn(); modeColumn = new GridColumn(); batchColumn = new GridColumn(); attemptsColumn = new GridColumn(); orderColumn = new GridColumn(); activeColumn = new GridColumn(); continueOnErrorColumn = new GridColumn(); timeoutColumn = new GridColumn(); scheduleTypeColumn = new GridColumn(); intervalColumn = new GridColumn(); executionTimeColumn = new GridColumn(); timeZoneColumn = new GridColumn(); preventConcurrentColumn = new GridColumn(); scheduleActiveColumn = new GridColumn(); nextExecutionColumn = new GridColumn(); lastExecutionColumn = new GridColumn();
        ((System.ComponentModel.ISupportInitialize)tabs).BeginInit(); tabs.SuspendLayout(); generalTab.SuspendLayout(); entitiesTab.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)companyEdit.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)codeEdit.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)nameEdit.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)descriptionEdit.Properties).BeginInit(); ((System.ComponentModel.ISupportInitialize)entitiesGrid).BeginInit(); ((System.ComponentModel.ISupportInitialize)entitiesView).BeginInit(); ((System.ComponentModel.ISupportInitialize)directionRepository).BeginInit(); ((System.ComponentModel.ISupportInitialize)modeRepository).BeginInit(); ((System.ComponentModel.ISupportInitialize)scheduleRepository).BeginInit(); SuspendLayout();
        tabs.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right; tabs.Location = new Point(12, 12); tabs.Name = "tabs"; tabs.SelectedTabPage = generalTab; tabs.Size = new Size(1136, 600); tabs.TabPages.AddRange(new[] { generalTab, entitiesTab }); tabs.TabIndex = 0;
        generalTab.Controls.AddRange(new Control[] { companyLabel, companyEdit, codeLabel, codeEdit, nameLabel, nameEdit, descriptionLabel, descriptionEdit, statusLabel }); generalTab.Name = "generalTab"; generalTab.Size = new Size(1134, 575); generalTab.Text = "General";
        companyLabel.Location = new Point(24, 25); companyLabel.Name = "companyLabel"; companyLabel.Text = "Empresa SAP"; companyEdit.Location = new Point(160, 22); companyEdit.Name = "companyEdit"; companyEdit.Properties.Buttons.Add(new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)); companyEdit.Properties.NullText = "Seleccione..."; companyEdit.Properties.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor; companyEdit.Size = new Size(420, 22); companyEdit.TabIndex = 0;
        codeLabel.Location = new Point(24, 65); codeLabel.Name = "codeLabel"; codeLabel.Text = "Codigo"; codeEdit.Location = new Point(160, 62); codeEdit.Name = "codeEdit"; codeEdit.Properties.MaxLength = 50; codeEdit.Size = new Size(220, 22); codeEdit.TabIndex = 1;
        nameLabel.Location = new Point(24, 105); nameLabel.Name = "nameLabel"; nameLabel.Text = "Nombre"; nameEdit.Location = new Point(160, 102); nameEdit.Name = "nameEdit"; nameEdit.Properties.MaxLength = 150; nameEdit.Size = new Size(560, 22); nameEdit.TabIndex = 2;
        descriptionLabel.Location = new Point(24, 145); descriptionLabel.Name = "descriptionLabel"; descriptionLabel.Text = "Descripcion"; descriptionEdit.Location = new Point(160, 142); descriptionEdit.Name = "descriptionEdit"; descriptionEdit.Properties.MaxLength = 500; descriptionEdit.Size = new Size(700, 96); descriptionEdit.TabIndex = 3;
        statusLabel.Location = new Point(160, 258); statusLabel.Name = "statusLabel"; statusLabel.Text = "Estado";
        entitiesTab.Controls.Add(entitiesGrid); entitiesTab.Name = "entitiesTab"; entitiesTab.Size = new Size(1134, 575); entitiesTab.Text = "Entidades y programacion";
        entitiesGrid.Dock = DockStyle.Fill; entitiesGrid.Location = new Point(0, 0); entitiesGrid.MainView = entitiesView; entitiesGrid.Name = "entitiesGrid"; entitiesGrid.RepositoryItems.AddRange(new RepositoryItem[] { directionRepository, modeRepository, scheduleRepository }); entitiesGrid.Size = new Size(1134, 575); entitiesGrid.TabIndex = 0; entitiesGrid.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] { entitiesView });
        entitiesView.Columns.AddRange(new[] { entityCodeColumn, entityNameColumn, directionColumn, modeColumn, batchColumn, attemptsColumn, orderColumn, activeColumn, continueOnErrorColumn, timeoutColumn, scheduleTypeColumn, intervalColumn, executionTimeColumn, timeZoneColumn, preventConcurrentColumn, scheduleActiveColumn, nextExecutionColumn, lastExecutionColumn }); entitiesView.GridControl = entitiesGrid; entitiesView.Name = "entitiesView"; entitiesView.OptionsView.ShowGroupPanel = false; entitiesView.OptionsView.ColumnAutoWidth = false;
        directionRepository.AutoHeight = false; directionRepository.Buttons.Add(new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)); directionRepository.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
        modeRepository.AutoHeight = false; modeRepository.Buttons.Add(new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)); modeRepository.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
        scheduleRepository.AutoHeight = false; scheduleRepository.Buttons.Add(new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)); scheduleRepository.TextEditStyle = DevExpress.XtraEditors.Controls.TextEditStyles.DisableTextEditor;
        entityCodeColumn.Caption = "Entidad"; entityCodeColumn.FieldName = "EntityCode"; entityCodeColumn.Visible = true; entityCodeColumn.VisibleIndex = 0; entityCodeColumn.Width = 115; entityCodeColumn.OptionsColumn.ReadOnly = true;
        entityNameColumn.Caption = "Nombre"; entityNameColumn.FieldName = "EntityName"; entityNameColumn.Visible = true; entityNameColumn.VisibleIndex = 1; entityNameColumn.Width = 170; entityNameColumn.OptionsColumn.ReadOnly = true;
        directionColumn.Caption = "Direccion"; directionColumn.FieldName = "Direction"; directionColumn.Visible = true; directionColumn.VisibleIndex = 2; directionColumn.Width = 110; directionColumn.ColumnEdit = directionRepository;
        modeColumn.Caption = "Modo"; modeColumn.FieldName = "SyncMode"; modeColumn.Visible = true; modeColumn.VisibleIndex = 3; modeColumn.Width = 90; modeColumn.ColumnEdit = modeRepository;
        batchColumn.Caption = "Lote"; batchColumn.FieldName = "BatchSize"; batchColumn.Visible = true; batchColumn.VisibleIndex = 4; batchColumn.Width = 70;
        attemptsColumn.Caption = "Intentos"; attemptsColumn.FieldName = "MaxAttempts"; attemptsColumn.Visible = true; attemptsColumn.VisibleIndex = 5; attemptsColumn.Width = 70;
        orderColumn.Caption = "Orden"; orderColumn.FieldName = "ExecutionOrder"; orderColumn.Visible = true; orderColumn.VisibleIndex = 6; orderColumn.Width = 65;
        activeColumn.Caption = "Activa"; activeColumn.FieldName = "IsActive"; activeColumn.Visible = true; activeColumn.VisibleIndex = 7; activeColumn.Width = 65;
        continueOnErrorColumn.Caption = "Continuar con error"; continueOnErrorColumn.FieldName = "ContinueOnError"; continueOnErrorColumn.Visible = true; continueOnErrorColumn.VisibleIndex = 8; continueOnErrorColumn.Width = 115;
        timeoutColumn.Caption = "Timeout (min)"; timeoutColumn.FieldName = "ExecutionTimeoutMinutes"; timeoutColumn.Visible = true; timeoutColumn.VisibleIndex = 9; timeoutColumn.Width = 90;
        scheduleTypeColumn.Caption = "Agenda"; scheduleTypeColumn.FieldName = "ScheduleType"; scheduleTypeColumn.Visible = true; scheduleTypeColumn.VisibleIndex = 10; scheduleTypeColumn.Width = 90; scheduleTypeColumn.ColumnEdit = scheduleRepository;
        intervalColumn.Caption = "Minutos"; intervalColumn.FieldName = "IntervalMinutes"; intervalColumn.Visible = true; intervalColumn.VisibleIndex = 11; intervalColumn.Width = 70;
        executionTimeColumn.Caption = "Hora"; executionTimeColumn.FieldName = "ExecutionTime"; executionTimeColumn.Visible = true; executionTimeColumn.VisibleIndex = 12; executionTimeColumn.Width = 80;
        timeZoneColumn.Caption = "Zona horaria"; timeZoneColumn.FieldName = "TimeZoneId"; timeZoneColumn.Visible = true; timeZoneColumn.VisibleIndex = 13; timeZoneColumn.Width = 150;
        preventConcurrentColumn.Caption = "Evitar simultaneas"; preventConcurrentColumn.FieldName = "PreventConcurrentExecutions"; preventConcurrentColumn.Visible = true; preventConcurrentColumn.VisibleIndex = 14; preventConcurrentColumn.Width = 115;
        scheduleActiveColumn.Caption = "Agenda activa"; scheduleActiveColumn.FieldName = "ScheduleIsActive"; scheduleActiveColumn.Visible = true; scheduleActiveColumn.VisibleIndex = 15; scheduleActiveColumn.Width = 90;
        nextExecutionColumn.Caption = "Proxima ejecucion"; nextExecutionColumn.FieldName = "NextExecutionAtUtc"; nextExecutionColumn.Visible = true; nextExecutionColumn.VisibleIndex = 16; nextExecutionColumn.Width = 145; nextExecutionColumn.OptionsColumn.ReadOnly = true;
        lastExecutionColumn.Caption = "Ultima ejecucion"; lastExecutionColumn.FieldName = "LastExecutionAtUtc"; lastExecutionColumn.Visible = true; lastExecutionColumn.VisibleIndex = 17; lastExecutionColumn.Width = 145; lastExecutionColumn.OptionsColumn.ReadOnly = true;
        AutoScaleDimensions = new SizeF(7F, 15F); AutoScaleMode = AutoScaleMode.Font; ClientSize = new Size(1160, 680); Controls.Add(tabs); FormBorderStyle = FormBorderStyle.Sizable; MaximizeBox = true; MinimumSize = new Size(980, 600); Name = "SapSyncProfileEditForm"; Text = "Perfil SAP";
        ((System.ComponentModel.ISupportInitialize)tabs).EndInit(); tabs.ResumeLayout(false); generalTab.ResumeLayout(false); generalTab.PerformLayout(); entitiesTab.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)companyEdit.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)codeEdit.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)nameEdit.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)descriptionEdit.Properties).EndInit(); ((System.ComponentModel.ISupportInitialize)entitiesGrid).EndInit(); ((System.ComponentModel.ISupportInitialize)entitiesView).EndInit(); ((System.ComponentModel.ISupportInitialize)directionRepository).EndInit(); ((System.ComponentModel.ISupportInitialize)modeRepository).EndInit(); ((System.ComponentModel.ISupportInitialize)scheduleRepository).EndInit(); ResumeLayout(false);
    }
    protected override void Dispose(bool disposing) { if (disposing) components?.Dispose(); base.Dispose(disposing); }
}
