namespace NuanSystem.WinForms.Forms.SecurityAccess;

partial class RoleAccessForm
{
    private System.ComponentModel.IContainer components = null;

    private void InitializeComponent()
    {
        toolbarPanel = new Panel();
        titleLabel = new Label();
        saveButton = new DevExpress.XtraEditors.SimpleButton();
        mainLayout = new TableLayoutPanel();
        rolesPanel = new Panel();
        rolesList = new ListBox();
        rolesHeaderLabel = new Label();
        menusPanel = new Panel();
        menuTree = new TreeView();
        menusHeaderLabel = new Label();
        operationsPanel = new Panel();
        operationsContentPanel = new Panel();
        operationsGrid = new DataGridView();
        formLabel = new Label();
        operationsHeaderLabel = new Label();
        toolbarPanel.SuspendLayout();
        mainLayout.SuspendLayout();
        rolesPanel.SuspendLayout();
        menusPanel.SuspendLayout();
        operationsPanel.SuspendLayout();
        operationsContentPanel.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)operationsGrid).BeginInit();
        SuspendLayout();
        toolbarPanel.BackColor = Color.White;
        toolbarPanel.Controls.Add(saveButton);
        toolbarPanel.Controls.Add(titleLabel);
        toolbarPanel.Dock = DockStyle.Top;
        toolbarPanel.Location = new Point(0, 0);
        toolbarPanel.Name = "toolbarPanel";
        toolbarPanel.Padding = new Padding(12, 6, 12, 6);
        toolbarPanel.Size = new Size(1100, 48);
        toolbarPanel.TabIndex = 0;
        titleLabel.Dock = DockStyle.Left;
        titleLabel.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
        titleLabel.ForeColor = Color.FromArgb(23, 32, 51);
        titleLabel.Location = new Point(12, 6);
        titleLabel.Name = "titleLabel";
        titleLabel.Size = new Size(280, 36);
        titleLabel.TabIndex = 0;
        titleLabel.Text = "Accesos por Rol";
        titleLabel.TextAlign = ContentAlignment.MiddleLeft;
        saveButton.Dock = DockStyle.Right;
        saveButton.Location = new Point(958, 6);
        saveButton.Name = "saveButton";
        saveButton.Size = new Size(130, 36);
        saveButton.TabIndex = 1;
        saveButton.Text = "Guardar cambios";
        mainLayout.ColumnCount = 3;
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 240F));
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 300F));
        mainLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        mainLayout.Controls.Add(rolesPanel, 0, 0);
        mainLayout.Controls.Add(menusPanel, 1, 0);
        mainLayout.Controls.Add(operationsPanel, 2, 0);
        mainLayout.Dock = DockStyle.Fill;
        mainLayout.Location = new Point(0, 48);
        mainLayout.Name = "mainLayout";
        mainLayout.RowCount = 1;
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        mainLayout.Size = new Size(1100, 592);
        mainLayout.TabIndex = 1;
        rolesPanel.BackColor = Color.White;
        rolesPanel.Controls.Add(rolesList);
        rolesPanel.Controls.Add(rolesHeaderLabel);
        rolesPanel.Dock = DockStyle.Fill;
        rolesPanel.Location = new Point(0, 0);
        rolesPanel.Margin = new Padding(0);
        rolesPanel.Name = "rolesPanel";
        rolesPanel.Size = new Size(240, 592);
        rolesPanel.TabIndex = 0;
        rolesList.BorderStyle = BorderStyle.FixedSingle;
        rolesList.Dock = DockStyle.Fill;
        rolesList.Font = new Font("Segoe UI", 9F);
        rolesList.FormattingEnabled = true;
        rolesList.ItemHeight = 15;
        rolesList.Location = new Point(0, 34);
        rolesList.Name = "rolesList";
        rolesList.Size = new Size(240, 558);
        rolesList.TabIndex = 1;
        rolesHeaderLabel.BackColor = Color.FromArgb(248, 250, 252);
        rolesHeaderLabel.Dock = DockStyle.Top;
        rolesHeaderLabel.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
        rolesHeaderLabel.ForeColor = Color.FromArgb(71, 85, 105);
        rolesHeaderLabel.Location = new Point(0, 0);
        rolesHeaderLabel.Name = "rolesHeaderLabel";
        rolesHeaderLabel.Padding = new Padding(10, 10, 10, 0);
        rolesHeaderLabel.Size = new Size(240, 34);
        rolesHeaderLabel.TabIndex = 0;
        rolesHeaderLabel.Text = "ROLES";
        menusPanel.BackColor = Color.White;
        menusPanel.Controls.Add(menuTree);
        menusPanel.Controls.Add(menusHeaderLabel);
        menusPanel.Dock = DockStyle.Fill;
        menusPanel.Location = new Point(240, 0);
        menusPanel.Margin = new Padding(0);
        menusPanel.Name = "menusPanel";
        menusPanel.Size = new Size(300, 592);
        menusPanel.TabIndex = 1;
        menuTree.BorderStyle = BorderStyle.FixedSingle;
        menuTree.CheckBoxes = true;
        menuTree.Dock = DockStyle.Fill;
        menuTree.Font = new Font("Segoe UI", 9F);
        menuTree.Location = new Point(0, 34);
        menuTree.Name = "menuTree";
        menuTree.Size = new Size(300, 558);
        menuTree.TabIndex = 1;
        menusHeaderLabel.BackColor = Color.FromArgb(248, 250, 252);
        menusHeaderLabel.Dock = DockStyle.Top;
        menusHeaderLabel.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
        menusHeaderLabel.ForeColor = Color.FromArgb(71, 85, 105);
        menusHeaderLabel.Location = new Point(0, 0);
        menusHeaderLabel.Name = "menusHeaderLabel";
        menusHeaderLabel.Padding = new Padding(10, 10, 10, 0);
        menusHeaderLabel.Size = new Size(300, 34);
        menusHeaderLabel.TabIndex = 0;
        menusHeaderLabel.Text = "MENUS";
        operationsPanel.BackColor = Color.White;
        operationsPanel.Controls.Add(operationsContentPanel);
        operationsPanel.Controls.Add(operationsHeaderLabel);
        operationsPanel.Dock = DockStyle.Fill;
        operationsPanel.Location = new Point(540, 0);
        operationsPanel.Margin = new Padding(0);
        operationsPanel.Name = "operationsPanel";
        operationsPanel.Size = new Size(560, 592);
        operationsPanel.TabIndex = 2;
        operationsContentPanel.Controls.Add(operationsGrid);
        operationsContentPanel.Controls.Add(formLabel);
        operationsContentPanel.Dock = DockStyle.Fill;
        operationsContentPanel.Location = new Point(0, 34);
        operationsContentPanel.Name = "operationsContentPanel";
        operationsContentPanel.Size = new Size(560, 558);
        operationsContentPanel.TabIndex = 1;
        operationsGrid.AllowUserToAddRows = false;
        operationsGrid.AllowUserToDeleteRows = false;
        operationsGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        operationsGrid.BackgroundColor = Color.White;
        operationsGrid.BorderStyle = BorderStyle.FixedSingle;
        operationsGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        operationsGrid.Dock = DockStyle.Fill;
        operationsGrid.Location = new Point(0, 34);
        operationsGrid.Name = "operationsGrid";
        operationsGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        operationsGrid.Size = new Size(560, 524);
        operationsGrid.TabIndex = 1;
        formLabel.BackColor = Color.FromArgb(248, 250, 252);
        formLabel.Dock = DockStyle.Top;
        formLabel.Font = new Font("Segoe UI", 9F);
        formLabel.Location = new Point(0, 0);
        formLabel.Name = "formLabel";
        formLabel.Padding = new Padding(10, 9, 10, 0);
        formLabel.Size = new Size(560, 34);
        formLabel.TabIndex = 0;
        formLabel.Text = "Formulario: -";
        operationsHeaderLabel.BackColor = Color.FromArgb(248, 250, 252);
        operationsHeaderLabel.Dock = DockStyle.Top;
        operationsHeaderLabel.Font = new Font("Segoe UI", 8.5F, FontStyle.Bold);
        operationsHeaderLabel.ForeColor = Color.FromArgb(71, 85, 105);
        operationsHeaderLabel.Location = new Point(0, 0);
        operationsHeaderLabel.Name = "operationsHeaderLabel";
        operationsHeaderLabel.Padding = new Padding(10, 10, 10, 0);
        operationsHeaderLabel.Size = new Size(560, 34);
        operationsHeaderLabel.TabIndex = 0;
        operationsHeaderLabel.Text = "OPERACIONES";
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(245, 247, 250);
        ClientSize = new Size(1100, 640);
        Controls.Add(mainLayout);
        Controls.Add(toolbarPanel);
        Font = new Font("Segoe UI", 9F);
        MinimumSize = new Size(980, 560);
        Name = "RoleAccessForm";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "Accesos por rol";
        toolbarPanel.ResumeLayout(false);
        mainLayout.ResumeLayout(false);
        rolesPanel.ResumeLayout(false);
        menusPanel.ResumeLayout(false);
        operationsPanel.ResumeLayout(false);
        operationsContentPanel.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)operationsGrid).EndInit();
        ResumeLayout(false);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    private Panel toolbarPanel;
    private Label titleLabel;
    private DevExpress.XtraEditors.SimpleButton saveButton;
    private TableLayoutPanel mainLayout;
    private Panel rolesPanel;
    private ListBox rolesList;
    private Label rolesHeaderLabel;
    private Panel menusPanel;
    private TreeView menuTree;
    private Label menusHeaderLabel;
    private Panel operationsPanel;
    private Panel operationsContentPanel;
    private DataGridView operationsGrid;
    private Label formLabel;
    private Label operationsHeaderLabel;
}
