using FluentValidation;
using MediatR;
using Microsoft.Extensions.DependencyInjection;
using NuanSystem.Application.Abstractions.Sap;
using NuanSystem.Application.Abstractions.SapSync;
using NuanSystem.Application.Abstractions.Operations;
using NuanSystem.Application.Abstractions.Sync;
using NuanSystem.Application.Abstractions.Tenancy;
using NuanSystem.Application.Abstractions.Common;
using NuanSystem.Application.Common;
using NuanSystem.Application.Common.Behaviors;
using NuanSystem.Application.Features.SapSync.Handlers;
using NuanSystem.Application.Features.SapSync.Services;
using NuanSystem.Application.Features.SapSync.Profiles.Services;
using NuanSystem.Application.Features.SapSync.Executions;
using NuanSystem.Application.Features.SapSync.Warehouses.Handlers;
using NuanSystem.Application.Features.SapSync.Warehouses.Services;
using NuanSystem.Application.Features.SapSync.Countries.Contracts;
using NuanSystem.Application.Features.SapSync.Countries.Handlers;
using NuanSystem.Application.Features.SapSync.Countries.Services;
using NuanSystem.Application.Features.SapSync.Provinces.Contracts;
using NuanSystem.Application.Features.SapSync.Provinces.Handlers;
using NuanSystem.Application.Features.SapSync.Provinces.Services;
using NuanSystem.Application.Features.SapSync.Cities.Contracts;
using NuanSystem.Application.Features.SapSync.Cities.Handlers;
using NuanSystem.Application.Features.SapSync.Cities.Services;
using NuanSystem.Application.Features.Operations;
using NuanSystem.Application.Features.SriDocuments.Services;
using NuanSystem.Application.Features.SriTxtImports.Services;
using NuanSystem.Application.Features.BusinessPartners.Commands;
using NuanSystem.Application.Features.BusinessPartners.SyncConflicts;
using NuanSystem.Application.Features.Carriers.Commands;
using NuanSystem.Application.Features.FinancialCatalogs.Catalogs.Commands;
using NuanSystem.Application.Features.FinancialCatalogs.PriceLists.Commands;
using NuanSystem.Application.Features.Definitions.Inventory.ItemFamilies.Commands;
using NuanSystem.Application.Features.Definitions.Inventory.ItemBrands.Commands;
using NuanSystem.Application.Features.Definitions.Inventory.UnitMeasures.Commands;
using NuanSystem.Application.Features.Definitions.Inventory.ProductTypes.Commands;
using NuanSystem.Application.Features.Definitions.Inventory.ItemLines.Commands;
using NuanSystem.Application.Features.Definitions.Inventory.ItemSubgroups.Commands;
using NuanSystem.Application.Features.Definitions.Inventory.ItemOrigins.Commands;
using NuanSystem.Application.Features.Definitions.Inventory.ReplenishmentMethods.Commands;
using NuanSystem.Application.Features.Definitions.Inventory.StorageConditions.Commands;
using NuanSystem.Application.Features.GeneralInventory.ItemGroups.Commands;
using NuanSystem.Application.Features.GeneralInventory.Warehouses.Commands;
using NuanSystem.Application.Features.Definitions.General.Cities.Commands;
using NuanSystem.Application.Features.Definitions.General.Countries.Commands;
using NuanSystem.Application.Features.Definitions.General.Provinces.Commands;
using NuanSystem.Application.Features.Items.Commands;
using NuanSystem.Application.Features.TaxCatalogs.Taxes.Commands;
using NuanSystem.Application.Features.Sync.Configuration.Services;
using NuanSystem.Application.Features.Sync.Execution.Services;
using NuanSystem.Application.Features.Sync.EntityDefinitions.Services;
using NuanSystem.Application.Features.Sync.Services;
using NuanSystem.Application.Features.TenantConfiguration.Services;
using System.Reflection;

namespace NuanSystem.Application.DependencyInjection;

public static class ApplicationServiceRegistration
{
    public static IServiceCollection AddApplicationServices(this IServiceCollection services)
    {
        var assembly = Assembly.GetExecutingAssembly();

        services.AddMediatR(configuration =>
        {
            configuration.RegisterServicesFromAssembly(assembly);
            configuration.AddOpenBehavior(typeof(LoggingBehavior<,>));
            configuration.AddOpenBehavior(typeof(ValidationBehavior<,>));
        });

        services.AddValidatorsFromAssembly(assembly);
        services.AddScoped<ISapSupplierImportService, SapSupplierImportService>();
        services.AddScoped<ISapWarehouseImportService, SapWarehouseImportService>();
        services.AddScoped<ISapCountryImportService, SapCountryImportService>();
        services.AddScoped<ISapProvinceImportService, SapProvinceImportService>();
        services.AddScoped<ISapCityImportService, SapCityImportService>();
        services.AddScoped<ISapItemImportService, SapItemImportService>();
        services.AddScoped<ISapPurchaseOrderImportService, SapPurchaseOrderImportService>();
        services.AddScoped<ISapPaymentTermImportService, SapPaymentTermImportService>();
        services.AddScoped<ISapSyncOrchestrator, SapSyncOrchestrator>();
        services.AddScoped<ISapSyncScheduler, SapSyncScheduler>();
        services.AddScoped<ISapSyncExecutionLeaseCoordinator, SapSyncExecutionLeaseCoordinator>();
        services.AddScoped<ISapSyncExecutionRetryService, SapSyncExecutionRetryService>();
        services.AddScoped<ISapSyncScheduledExecutionPreparer, SapSyncScheduledExecutionPreparer>();
        services.AddSingleton<SapSyncScheduleCalculator>();
        services.AddScoped<ISapSyncJobRunner, SapSyncJobRunner>();
        services.AddScoped<ISapSyncLockService, SapSyncLockService>();
        services.AddScoped<ISapSyncWatermarkService, SapSyncWatermarkService>();
        services.AddScoped<ISapSyncLogService, SapSyncLogService>();
        services.AddScoped<ISapSyncRetryPolicy, SapSyncRetryPolicy>();
        services.AddScoped<ISapSyncProfileValidationService, SapSyncProfileValidationService>();
        services.AddScoped<IWorkerHeartbeatService, WorkerHeartbeatService>();
        services.AddScoped<ISapSyncEntityHandler, SapSupplierSyncHandler>();
        services.AddScoped<ISapSyncEntityHandler, SapItemSyncHandler>();
        services.AddScoped<ISapSyncEntityHandler, SapPurchaseOrderSyncHandler>();
        services.AddScoped<ISapSyncEntityHandler, SapPaymentTermSyncHandler>();
        services.AddScoped<ISapSyncEntityHandler, SapWarehouseSyncHandler>();
        services.AddScoped<ISapSyncEntityHandler, SapCountrySyncHandler>();
        services.AddScoped<ISapSyncEntityHandler, SapProvinceSyncHandler>();
        services.AddScoped<ISapSyncEntityHandler, SapCitySyncHandler>();
        services.AddScoped<ISapSyncScheduledExecutionProcessor, SapWarehouseExecutionProcessor>();
        services.AddScoped<ISapSyncScheduledExecutionProcessor, SapCountryExecutionProcessor>();
        services.AddScoped<ISapSyncScheduledExecutionProcessor, SapProvinceExecutionProcessor>();
        services.AddScoped<ISapSyncScheduledExecutionProcessor, SapCityExecutionProcessor>();
        services.AddScoped<ISapSyncExecutionRetryProcessor, SapWarehouseExecutionRetryProcessor>();
        services.AddScoped<ISapSyncExecutionRetryProcessor, SapCountryExecutionRetryProcessor>();
        services.AddScoped<ISapSyncExecutionRetryProcessor, SapProvinceExecutionRetryProcessor>();
        services.AddScoped<ISapSyncExecutionRetryProcessor, SapCityExecutionRetryProcessor>();
        services.AddScoped<SapWarehouseRecordProcessor>();
        services.AddScoped<SapCountryRecordProcessor>();
        services.AddScoped<SapProvinceRecordProcessor>();
        services.AddScoped<SapCityRecordProcessor>();
        services.AddScoped<ITenantFeatureService, TenantFeatureService>();
        services.AddScoped<ITenantIntegrationService, TenantIntegrationService>();
        services.AddScoped<ISriDocumentQueuePolicy, SriDocumentQueuePolicy>();
        services.AddSingleton<ISriTxtFileParser, SriTxtFileParser>();
        services.AddScoped<IEntityOwnershipService, EntityOwnershipService>();
        services.AddSingleton<ISystemClock, SystemClock>();
        services.AddScoped<ISyncEventPublisher, SyncEventPublisher>();
        services.AddScoped<ISyncEventPayloadFactory, SyncEventPayloadFactory>();
        services.AddScoped<ISyncRoutingService, SyncRoutingService>();
        services.AddScoped<ILocalSyncOutboxPromotionService, LocalSyncOutboxPromotionService>();
        services.AddScoped<IBusinessPartnerLocalOutboxWriter, BusinessPartnerLocalOutboxWriter>();
        services.AddSingleton<IBusinessPartnerSyncConflictResolutionPlanner, BusinessPartnerSyncConflictResolutionPlanner>();
        services.AddScoped<ICarrierLocalOutboxWriter, CarrierLocalOutboxWriter>();
        services.AddScoped<ICurrencyLocalOutboxWriter, CurrencyLocalOutboxWriter>();
        services.AddScoped<IPriceListLocalOutboxWriter, PriceListLocalOutboxWriter>();
        services.AddScoped<ITaxLocalOutboxWriter, TaxLocalOutboxWriter>();
        services.AddScoped<IItemLocalOutboxWriter, ItemLocalOutboxWriter>();
        services.AddScoped<IItemFamilyLocalOutboxWriter, ItemFamilyLocalOutboxWriter>();
        services.AddScoped<IItemBrandLocalOutboxWriter, ItemBrandLocalOutboxWriter>();
        services.AddScoped<IUnitMeasureLocalOutboxWriter, UnitMeasureLocalOutboxWriter>();
        services.AddScoped<IProductTypeLocalOutboxWriter, ProductTypeLocalOutboxWriter>();
        services.AddScoped<IItemLineLocalOutboxWriter, ItemLineLocalOutboxWriter>();
        services.AddScoped<IItemSubgroupLocalOutboxWriter, ItemSubgroupLocalOutboxWriter>();
        services.AddScoped<IItemOriginLocalOutboxWriter, ItemOriginLocalOutboxWriter>();
        services.AddScoped<IReplenishmentMethodLocalOutboxWriter, ReplenishmentMethodLocalOutboxWriter>();
        services.AddScoped<IStorageConditionLocalOutboxWriter, StorageConditionLocalOutboxWriter>();
        services.AddScoped<IItemGroupLocalOutboxWriter, ItemGroupLocalOutboxWriter>();
        services.AddScoped<IWarehouseLocalOutboxWriter, WarehouseLocalOutboxWriter>();
        services.AddScoped<ICountryLocalOutboxWriter, CountryLocalOutboxWriter>();
        services.AddScoped<IProvinceLocalOutboxWriter, ProvinceLocalOutboxWriter>();
        services.AddScoped<ICityLocalOutboxWriter, CityLocalOutboxWriter>();
        services.AddSingleton<ISyncDistributionPolicyEvaluator, SyncDistributionPolicyEvaluator>();
        services.AddScoped<ISyncProfileValidationService, SyncProfileValidationService>();
        services.AddScoped<ISyncEntityCatalogService, SyncEntityCatalogService>();
        services.AddScoped<ISyncProfileExecutionService, SyncProfileExecutionService>();
        services.AddScoped<IPurchaseOrderRoutingService, PurchaseOrderRoutingService>();
        services.AddScoped<ISyncScheduleCalculator, SyncScheduleCalculator>();

        return services;
    }
}
