using System.Drawing;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;

namespace NuanSystem.WinForms.Forms.BusinessPartners;

partial class SupplierAccountingAccountEditDialog
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        pnlMain = new PanelControl();
        lblAccountingAccountType = new LabelControl();
        lueAccountingAccountType = new LookUpEdit();
        lblAccountingAccount = new LabelControl();
        slueAccountingAccount = new LookUpEdit();
        lblAccountingDimension1 = new LabelControl();
        lueAccountingDimension1 = new LookUpEdit();
        lblAccountingDimension2 = new LabelControl();
        lueAccountingDimension2 = new LookUpEdit();
        lblAccountingDimension3 = new LabelControl();
        lueAccountingDimension3 = new LookUpEdit();
        lblAccountingDimension4 = new LabelControl();
        lueAccountingDimension4 = new LookUpEdit();
        lblAccountingDimension5 = new LabelControl();
        lueAccountingDimension5 = new LookUpEdit();
        lblAccountingAccountDefault = new LabelControl();
        tglAccountingAccountDefault = new ToggleSwitch();
        lblAccountingAccountDefaultValue = new LabelControl();
        lblAccountingAccountActive = new LabelControl();
        tglAccountingAccountActive = new ToggleSwitch();
        lblAccountingAccountActiveValue = new LabelControl();
        lblAccountingAccountNotes = new LabelControl();
        memAccountingAccountNotes = new MemoEdit();
        pnlFooter = new PanelControl();
        btnSaveAccountingAccount = new SimpleButton();
        btnCancelAccountingAccount = new SimpleButton();
        ((System.ComponentModel.ISupportInitialize)pnlMain).BeginInit();
        pnlMain.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)lueAccountingAccountType.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)slueAccountingAccount.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueAccountingDimension1.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueAccountingDimension2.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueAccountingDimension3.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueAccountingDimension4.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueAccountingDimension5.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tglAccountingAccountDefault.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tglAccountingAccountActive.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)memAccountingAccountNotes.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)pnlFooter).BeginInit();
        pnlFooter.SuspendLayout();
        SuspendLayout();
        // 
        // pnlMain
        // 
        pnlMain.BorderStyle = BorderStyles.NoBorder;
        pnlMain.Controls.Add(lblAccountingAccountType);
        pnlMain.Controls.Add(lueAccountingAccountType);
        pnlMain.Controls.Add(lblAccountingAccount);
        pnlMain.Controls.Add(slueAccountingAccount);
        pnlMain.Controls.Add(lblAccountingDimension1);
        pnlMain.Controls.Add(lueAccountingDimension1);
        pnlMain.Controls.Add(lblAccountingDimension2);
        pnlMain.Controls.Add(lueAccountingDimension2);
        pnlMain.Controls.Add(lblAccountingDimension3);
        pnlMain.Controls.Add(lueAccountingDimension3);
        pnlMain.Controls.Add(lblAccountingDimension4);
        pnlMain.Controls.Add(lueAccountingDimension4);
        pnlMain.Controls.Add(lblAccountingDimension5);
        pnlMain.Controls.Add(lueAccountingDimension5);
        pnlMain.Controls.Add(lblAccountingAccountDefault);
        pnlMain.Controls.Add(tglAccountingAccountDefault);
        pnlMain.Controls.Add(lblAccountingAccountDefaultValue);
        pnlMain.Controls.Add(lblAccountingAccountActive);
        pnlMain.Controls.Add(tglAccountingAccountActive);
        pnlMain.Controls.Add(lblAccountingAccountActiveValue);
        pnlMain.Controls.Add(lblAccountingAccountNotes);
        pnlMain.Controls.Add(memAccountingAccountNotes);
        pnlMain.Dock = DockStyle.Fill;
        pnlMain.Location = new Point(0, 0);
        pnlMain.Name = "pnlMain";
        pnlMain.Size = new Size(520, 340);
        pnlMain.TabIndex = 0;
        lblAccountingAccountType.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingAccountType.Appearance.Options.UseFont = true;
        lblAccountingAccountType.Location = new Point(22, 24);
        lblAccountingAccountType.Name = "lblAccountingAccountType";
        lblAccountingAccountType.Text = "Tipo:";
        lueAccountingAccountType.Location = new Point(214, 21);
        lueAccountingAccountType.Name = "lueAccountingAccountType";
        lueAccountingAccountType.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueAccountingAccountType.Properties.Appearance.Options.UseFont = true;
        lueAccountingAccountType.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueAccountingAccountType.Properties.NullText = string.Empty;
        lueAccountingAccountType.Size = new Size(270, 22);
        lueAccountingAccountType.TabIndex = 1;
        lblAccountingAccount.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingAccount.Appearance.Options.UseFont = true;
        lblAccountingAccount.Location = new Point(22, 52);
        lblAccountingAccount.Name = "lblAccountingAccount";
        lblAccountingAccount.Text = "Cuenta Contable:";
        slueAccountingAccount.Location = new Point(214, 49);
        slueAccountingAccount.Name = "slueAccountingAccount";
        slueAccountingAccount.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        slueAccountingAccount.Properties.Appearance.Options.UseFont = true;
        slueAccountingAccount.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        slueAccountingAccount.Properties.NullText = string.Empty;
        slueAccountingAccount.Size = new Size(270, 22);
        slueAccountingAccount.TabIndex = 3;
        lblAccountingDimension1.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingDimension1.Appearance.Options.UseFont = true;
        lblAccountingDimension1.Location = new Point(22, 80);
        lblAccountingDimension1.Name = "lblAccountingDimension1";
        lblAccountingDimension1.Text = "Dimensión 1 / Centro de Costo:";
        lueAccountingDimension1.Location = new Point(214, 77);
        lueAccountingDimension1.Name = "lueAccountingDimension1";
        lueAccountingDimension1.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueAccountingDimension1.Properties.Appearance.Options.UseFont = true;
        lueAccountingDimension1.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueAccountingDimension1.Properties.NullText = string.Empty;
        lueAccountingDimension1.Size = new Size(270, 22);
        lueAccountingDimension1.TabIndex = 5;
        lblAccountingDimension2.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingDimension2.Appearance.Options.UseFont = true;
        lblAccountingDimension2.Location = new Point(22, 108);
        lblAccountingDimension2.Name = "lblAccountingDimension2";
        lblAccountingDimension2.Text = "Dimensión 2 / Centro de Costo:";
        lueAccountingDimension2.Location = new Point(214, 105);
        lueAccountingDimension2.Name = "lueAccountingDimension2";
        lueAccountingDimension2.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueAccountingDimension2.Properties.Appearance.Options.UseFont = true;
        lueAccountingDimension2.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueAccountingDimension2.Properties.NullText = string.Empty;
        lueAccountingDimension2.Size = new Size(270, 22);
        lueAccountingDimension2.TabIndex = 7;
        lblAccountingDimension3.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingDimension3.Appearance.Options.UseFont = true;
        lblAccountingDimension3.Location = new Point(22, 136);
        lblAccountingDimension3.Name = "lblAccountingDimension3";
        lblAccountingDimension3.Text = "Dimensión 3 / Centro de Costo:";
        lueAccountingDimension3.Location = new Point(214, 133);
        lueAccountingDimension3.Name = "lueAccountingDimension3";
        lueAccountingDimension3.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueAccountingDimension3.Properties.Appearance.Options.UseFont = true;
        lueAccountingDimension3.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueAccountingDimension3.Properties.NullText = string.Empty;
        lueAccountingDimension3.Size = new Size(270, 22);
        lueAccountingDimension3.TabIndex = 9;
        lblAccountingDimension4.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingDimension4.Appearance.Options.UseFont = true;
        lblAccountingDimension4.Location = new Point(22, 164);
        lblAccountingDimension4.Name = "lblAccountingDimension4";
        lblAccountingDimension4.Text = "Dimensión 4 / Centro de Costo:";
        lueAccountingDimension4.Location = new Point(214, 161);
        lueAccountingDimension4.Name = "lueAccountingDimension4";
        lueAccountingDimension4.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueAccountingDimension4.Properties.Appearance.Options.UseFont = true;
        lueAccountingDimension4.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueAccountingDimension4.Properties.NullText = string.Empty;
        lueAccountingDimension4.Size = new Size(270, 22);
        lueAccountingDimension4.TabIndex = 11;
        lblAccountingDimension5.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingDimension5.Appearance.Options.UseFont = true;
        lblAccountingDimension5.Location = new Point(22, 192);
        lblAccountingDimension5.Name = "lblAccountingDimension5";
        lblAccountingDimension5.Text = "Dimensión 5 / Centro de Costo:";
        lueAccountingDimension5.Location = new Point(214, 189);
        lueAccountingDimension5.Name = "lueAccountingDimension5";
        lueAccountingDimension5.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueAccountingDimension5.Properties.Appearance.Options.UseFont = true;
        lueAccountingDimension5.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueAccountingDimension5.Properties.NullText = string.Empty;
        lueAccountingDimension5.Size = new Size(270, 22);
        lueAccountingDimension5.TabIndex = 13;
        lblAccountingAccountDefault.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingAccountDefault.Appearance.Options.UseFont = true;
        lblAccountingAccountDefault.Location = new Point(22, 220);
        lblAccountingAccountDefault.Name = "lblAccountingAccountDefault";
        lblAccountingAccountDefault.Text = "Predeterminada:";
        tglAccountingAccountDefault.Location = new Point(214, 215);
        tglAccountingAccountDefault.Name = "tglAccountingAccountDefault";
        tglAccountingAccountDefault.Properties.OffText = string.Empty;
        tglAccountingAccountDefault.Properties.OnText = string.Empty;
        tglAccountingAccountDefault.Size = new Size(50, 24);
        tglAccountingAccountDefault.TabIndex = 15;
        lblAccountingAccountDefaultValue.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingAccountDefaultValue.Appearance.Options.UseFont = true;
        lblAccountingAccountDefaultValue.Location = new Point(270, 220);
        lblAccountingAccountDefaultValue.Name = "lblAccountingAccountDefaultValue";
        lblAccountingAccountDefaultValue.Text = "Sí";
        lblAccountingAccountActive.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingAccountActive.Appearance.Options.UseFont = true;
        lblAccountingAccountActive.Location = new Point(22, 248);
        lblAccountingAccountActive.Name = "lblAccountingAccountActive";
        lblAccountingAccountActive.Text = "Activa:";
        tglAccountingAccountActive.Location = new Point(214, 243);
        tglAccountingAccountActive.Name = "tglAccountingAccountActive";
        tglAccountingAccountActive.Properties.OffText = string.Empty;
        tglAccountingAccountActive.Properties.OnText = string.Empty;
        tglAccountingAccountActive.Size = new Size(50, 24);
        tglAccountingAccountActive.TabIndex = 18;
        lblAccountingAccountActiveValue.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingAccountActiveValue.Appearance.Options.UseFont = true;
        lblAccountingAccountActiveValue.Location = new Point(270, 248);
        lblAccountingAccountActiveValue.Name = "lblAccountingAccountActiveValue";
        lblAccountingAccountActiveValue.Text = "Sí";
        lblAccountingAccountNotes.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAccountingAccountNotes.Appearance.Options.UseFont = true;
        lblAccountingAccountNotes.Location = new Point(22, 276);
        lblAccountingAccountNotes.Name = "lblAccountingAccountNotes";
        lblAccountingAccountNotes.Text = "Observaciones:";
        memAccountingAccountNotes.Location = new Point(214, 273);
        memAccountingAccountNotes.Name = "memAccountingAccountNotes";
        memAccountingAccountNotes.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        memAccountingAccountNotes.Properties.Appearance.Options.UseFont = true;
        memAccountingAccountNotes.Size = new Size(270, 52);
        memAccountingAccountNotes.TabIndex = 21;
        // 
        // pnlFooter
        // 
        pnlFooter.BorderStyle = BorderStyles.NoBorder;
        pnlFooter.Controls.Add(btnSaveAccountingAccount);
        pnlFooter.Controls.Add(btnCancelAccountingAccount);
        pnlFooter.Dock = DockStyle.Bottom;
        pnlFooter.Location = new Point(0, 340);
        pnlFooter.Name = "pnlFooter";
        pnlFooter.Size = new Size(520, 58);
        pnlFooter.TabIndex = 1;
        btnSaveAccountingAccount.Appearance.BackColor = Color.FromArgb(0, 102, 204);
        btnSaveAccountingAccount.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        btnSaveAccountingAccount.Appearance.ForeColor = Color.White;
        btnSaveAccountingAccount.Appearance.Options.UseBackColor = true;
        btnSaveAccountingAccount.Appearance.Options.UseFont = true;
        btnSaveAccountingAccount.Appearance.Options.UseForeColor = true;
        btnSaveAccountingAccount.Location = new Point(202, 12);
        btnSaveAccountingAccount.Name = "btnSaveAccountingAccount";
        btnSaveAccountingAccount.Size = new Size(108, 32);
        btnSaveAccountingAccount.TabIndex = 0;
        btnSaveAccountingAccount.Text = "Guardar";
        btnCancelAccountingAccount.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        btnCancelAccountingAccount.Appearance.Options.UseFont = true;
        btnCancelAccountingAccount.DialogResult = DialogResult.Cancel;
        btnCancelAccountingAccount.Location = new Point(324, 12);
        btnCancelAccountingAccount.Name = "btnCancelAccountingAccount";
        btnCancelAccountingAccount.Size = new Size(108, 32);
        btnCancelAccountingAccount.TabIndex = 1;
        btnCancelAccountingAccount.Text = "Cancelar";
        // 
        // SupplierAccountingAccountEditDialog
        // 
        AcceptButton = btnSaveAccountingAccount;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        CancelButton = btnCancelAccountingAccount;
        ClientSize = new Size(520, 398);
        Controls.Add(pnlMain);
        Controls.Add(pnlFooter);
        Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "SupplierAccountingAccountEditDialog";
        ShowInTaskbar = false;
        StartPosition = FormStartPosition.CenterParent;
        Text = "Nueva Cuenta Contable";
        ((System.ComponentModel.ISupportInitialize)pnlMain).EndInit();
        pnlMain.ResumeLayout(false);
        pnlMain.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)lueAccountingAccountType.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)slueAccountingAccount.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueAccountingDimension1.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueAccountingDimension2.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueAccountingDimension3.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueAccountingDimension4.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueAccountingDimension5.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tglAccountingAccountDefault.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tglAccountingAccountActive.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)memAccountingAccountNotes.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)pnlFooter).EndInit();
        pnlFooter.ResumeLayout(false);
        ResumeLayout(false);
    }

    private PanelControl pnlMain;
    private LabelControl lblAccountingAccountType;
    private LookUpEdit lueAccountingAccountType;
    private LabelControl lblAccountingAccount;
    private LookUpEdit slueAccountingAccount;
    private LabelControl lblAccountingDimension1;
    private LookUpEdit lueAccountingDimension1;
    private LabelControl lblAccountingDimension2;
    private LookUpEdit lueAccountingDimension2;
    private LabelControl lblAccountingDimension3;
    private LookUpEdit lueAccountingDimension3;
    private LabelControl lblAccountingDimension4;
    private LookUpEdit lueAccountingDimension4;
    private LabelControl lblAccountingDimension5;
    private LookUpEdit lueAccountingDimension5;
    private LabelControl lblAccountingAccountDefault;
    private ToggleSwitch tglAccountingAccountDefault;
    private LabelControl lblAccountingAccountDefaultValue;
    private LabelControl lblAccountingAccountActive;
    private ToggleSwitch tglAccountingAccountActive;
    private LabelControl lblAccountingAccountActiveValue;
    private LabelControl lblAccountingAccountNotes;
    private MemoEdit memAccountingAccountNotes;
    private PanelControl pnlFooter;
    private SimpleButton btnSaveAccountingAccount;
    private SimpleButton btnCancelAccountingAccount;
}
