using System.Drawing;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;

namespace NuanSystem.WinForms.Forms.BusinessPartners;

partial class SupplierAddressEditDialog
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        pnlMain = new PanelControl();
        lblAddressType = new LabelControl();
        lueAddressType = new LookUpEdit();
        lblAddressName = new LabelControl();
        txtAddressName = new TextEdit();
        lblMainStreet = new LabelControl();
        txtMainStreet = new TextEdit();
        lblSecondaryStreet = new LabelControl();
        txtSecondaryStreet = new TextEdit();
        lblAddressNumber = new LabelControl();
        txtAddressNumber = new TextEdit();
        lblAddressReference = new LabelControl();
        txtAddressReference = new TextEdit();
        lblDefaultBillingAddress = new LabelControl();
        tglDefaultBillingAddress = new ToggleSwitch();
        lblDefaultBillingAddressValue = new LabelControl();
        lblNeighborhood = new LabelControl();
        txtNeighborhood = new TextEdit();
        lblAddressProvince = new LabelControl();
        txtAddressProvince = new TextEdit();
        lblAddressCity = new LabelControl();
        txtAddressCity = new TextEdit();
        lblAddressCountry = new LabelControl();
        lueAddressCountry = new LookUpEdit();
        lblPostalCode = new LabelControl();
        txtPostalCode = new TextEdit();
        lblLatitude = new LabelControl();
        spnLatitude = new SpinEdit();
        lblLongitude = new LabelControl();
        spnLongitude = new SpinEdit();
        lblDefaultDeliveryAddress = new LabelControl();
        tglDefaultDeliveryAddress = new ToggleSwitch();
        lblDefaultDeliveryAddressValue = new LabelControl();
        lblAddressActive = new LabelControl();
        tglAddressActive = new ToggleSwitch();
        lblAddressActiveValue = new LabelControl();
        lblAddressNotes = new LabelControl();
        memAddressNotes = new MemoEdit();
        pnlFooter = new PanelControl();
        btnSaveAddress = new SimpleButton();
        btnCancelAddress = new SimpleButton();
        ((System.ComponentModel.ISupportInitialize)pnlMain).BeginInit();
        pnlMain.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)lueAddressType.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtAddressName.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtMainStreet.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtSecondaryStreet.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtAddressNumber.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtAddressReference.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tglDefaultBillingAddress.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtNeighborhood.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtAddressProvince.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtAddressCity.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueAddressCountry.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtPostalCode.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)spnLatitude.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)spnLongitude.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tglDefaultDeliveryAddress.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tglAddressActive.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)memAddressNotes.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)pnlFooter).BeginInit();
        pnlFooter.SuspendLayout();
        SuspendLayout();
        // 
        // pnlMain
        // 
        pnlMain.BorderStyle = BorderStyles.NoBorder;
        pnlMain.Controls.Add(lblAddressType);
        pnlMain.Controls.Add(lueAddressType);
        pnlMain.Controls.Add(lblAddressName);
        pnlMain.Controls.Add(txtAddressName);
        pnlMain.Controls.Add(lblMainStreet);
        pnlMain.Controls.Add(txtMainStreet);
        pnlMain.Controls.Add(lblSecondaryStreet);
        pnlMain.Controls.Add(txtSecondaryStreet);
        pnlMain.Controls.Add(lblAddressNumber);
        pnlMain.Controls.Add(txtAddressNumber);
        pnlMain.Controls.Add(lblAddressReference);
        pnlMain.Controls.Add(txtAddressReference);
        pnlMain.Controls.Add(lblDefaultBillingAddress);
        pnlMain.Controls.Add(tglDefaultBillingAddress);
        pnlMain.Controls.Add(lblDefaultBillingAddressValue);
        pnlMain.Controls.Add(lblNeighborhood);
        pnlMain.Controls.Add(txtNeighborhood);
        pnlMain.Controls.Add(lblAddressProvince);
        pnlMain.Controls.Add(txtAddressProvince);
        pnlMain.Controls.Add(lblAddressCity);
        pnlMain.Controls.Add(txtAddressCity);
        pnlMain.Controls.Add(lblAddressCountry);
        pnlMain.Controls.Add(lueAddressCountry);
        pnlMain.Controls.Add(lblPostalCode);
        pnlMain.Controls.Add(txtPostalCode);
        pnlMain.Controls.Add(lblLatitude);
        pnlMain.Controls.Add(spnLatitude);
        pnlMain.Controls.Add(lblLongitude);
        pnlMain.Controls.Add(spnLongitude);
        pnlMain.Controls.Add(lblDefaultDeliveryAddress);
        pnlMain.Controls.Add(tglDefaultDeliveryAddress);
        pnlMain.Controls.Add(lblDefaultDeliveryAddressValue);
        pnlMain.Controls.Add(lblAddressActive);
        pnlMain.Controls.Add(tglAddressActive);
        pnlMain.Controls.Add(lblAddressActiveValue);
        pnlMain.Controls.Add(lblAddressNotes);
        pnlMain.Controls.Add(memAddressNotes);
        pnlMain.Dock = DockStyle.Fill;
        pnlMain.Location = new Point(0, 0);
        pnlMain.Name = "pnlMain";
        pnlMain.Size = new Size(510, 336);
        pnlMain.TabIndex = 0;
        // 
        // left labels and editors
        // 
        lblAddressType.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAddressType.Appearance.Options.UseFont = true;
        lblAddressType.Location = new Point(20, 24);
        lblAddressType.Name = "lblAddressType";
        lblAddressType.Size = new Size(92, 15);
        lblAddressType.Text = "Tipo de Dirección:";
        lueAddressType.Location = new Point(146, 21);
        lueAddressType.Name = "lueAddressType";
        lueAddressType.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueAddressType.Properties.Appearance.Options.UseFont = true;
        lueAddressType.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueAddressType.Properties.NullText = string.Empty;
        lueAddressType.Size = new Size(150, 22);
        lueAddressType.TabIndex = 1;
        lblAddressName.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAddressName.Appearance.Options.UseFont = true;
        lblAddressName.Location = new Point(20, 54);
        lblAddressName.Name = "lblAddressName";
        lblAddressName.Size = new Size(120, 15);
        lblAddressName.Text = "Nombre de la Dirección:";
        txtAddressName.Location = new Point(146, 51);
        txtAddressName.Name = "txtAddressName";
        txtAddressName.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        txtAddressName.Properties.Appearance.Options.UseFont = true;
        txtAddressName.Size = new Size(150, 22);
        txtAddressName.TabIndex = 3;
        lblMainStreet.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblMainStreet.Appearance.Options.UseFont = true;
        lblMainStreet.Location = new Point(20, 84);
        lblMainStreet.Name = "lblMainStreet";
        lblMainStreet.Size = new Size(76, 15);
        lblMainStreet.Text = "Calle Principal:";
        txtMainStreet.Location = new Point(146, 81);
        txtMainStreet.Name = "txtMainStreet";
        txtMainStreet.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        txtMainStreet.Properties.Appearance.Options.UseFont = true;
        txtMainStreet.Size = new Size(150, 22);
        txtMainStreet.TabIndex = 5;
        lblSecondaryStreet.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblSecondaryStreet.Appearance.Options.UseFont = true;
        lblSecondaryStreet.Location = new Point(20, 114);
        lblSecondaryStreet.Name = "lblSecondaryStreet";
        lblSecondaryStreet.Size = new Size(91, 15);
        lblSecondaryStreet.Text = "Calle Secundaria:";
        txtSecondaryStreet.Location = new Point(146, 111);
        txtSecondaryStreet.Name = "txtSecondaryStreet";
        txtSecondaryStreet.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        txtSecondaryStreet.Properties.Appearance.Options.UseFont = true;
        txtSecondaryStreet.Size = new Size(150, 22);
        txtSecondaryStreet.TabIndex = 7;
        lblAddressNumber.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAddressNumber.Appearance.Options.UseFont = true;
        lblAddressNumber.Location = new Point(20, 144);
        lblAddressNumber.Name = "lblAddressNumber";
        lblAddressNumber.Size = new Size(47, 15);
        lblAddressNumber.Text = "Número:";
        txtAddressNumber.Location = new Point(146, 141);
        txtAddressNumber.Name = "txtAddressNumber";
        txtAddressNumber.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        txtAddressNumber.Properties.Appearance.Options.UseFont = true;
        txtAddressNumber.Size = new Size(150, 22);
        txtAddressNumber.TabIndex = 9;
        lblAddressReference.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAddressReference.Appearance.Options.UseFont = true;
        lblAddressReference.Location = new Point(20, 174);
        lblAddressReference.Name = "lblAddressReference";
        lblAddressReference.Size = new Size(59, 15);
        lblAddressReference.Text = "Referencia:";
        txtAddressReference.Location = new Point(146, 171);
        txtAddressReference.Name = "txtAddressReference";
        txtAddressReference.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        txtAddressReference.Properties.Appearance.Options.UseFont = true;
        txtAddressReference.Size = new Size(150, 22);
        txtAddressReference.TabIndex = 11;
        lblDefaultBillingAddress.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblDefaultBillingAddress.Appearance.Options.UseFont = true;
        lblDefaultBillingAddress.Location = new Point(20, 204);
        lblDefaultBillingAddress.Name = "lblDefaultBillingAddress";
        lblDefaultBillingAddress.Size = new Size(138, 15);
        lblDefaultBillingAddress.Text = "Predeterminada Facturación:";
        tglDefaultBillingAddress.Location = new Point(182, 199);
        tglDefaultBillingAddress.Name = "tglDefaultBillingAddress";
        tglDefaultBillingAddress.Properties.OffText = string.Empty;
        tglDefaultBillingAddress.Properties.OnText = string.Empty;
        tglDefaultBillingAddress.Size = new Size(48, 24);
        tglDefaultBillingAddress.TabIndex = 13;
        lblDefaultBillingAddressValue.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblDefaultBillingAddressValue.Appearance.Options.UseFont = true;
        lblDefaultBillingAddressValue.Location = new Point(236, 204);
        lblDefaultBillingAddressValue.Name = "lblDefaultBillingAddressValue";
        lblDefaultBillingAddressValue.Size = new Size(15, 15);
        lblDefaultBillingAddressValue.Text = "No";
        // 
        // right labels and editors
        // 
        lblNeighborhood.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblNeighborhood.Appearance.Options.UseFont = true;
        lblNeighborhood.Location = new Point(318, 24);
        lblNeighborhood.Name = "lblNeighborhood";
        lblNeighborhood.Size = new Size(74, 15);
        lblNeighborhood.Text = "Barrio / Sector:";
        txtNeighborhood.Location = new Point(410, 21);
        txtNeighborhood.Name = "txtNeighborhood";
        txtNeighborhood.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        txtNeighborhood.Properties.Appearance.Options.UseFont = true;
        txtNeighborhood.Size = new Size(80, 22);
        txtNeighborhood.TabIndex = 15;
        lblAddressProvince.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAddressProvince.Appearance.Options.UseFont = true;
        lblAddressProvince.Location = new Point(318, 54);
        lblAddressProvince.Name = "lblAddressProvince";
        lblAddressProvince.Size = new Size(50, 15);
        lblAddressProvince.Text = "Provincia:";
        txtAddressProvince.Location = new Point(410, 51);
        txtAddressProvince.Name = "txtAddressProvince";
        txtAddressProvince.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        txtAddressProvince.Properties.Appearance.Options.UseFont = true;
        txtAddressProvince.Size = new Size(80, 22);
        txtAddressProvince.TabIndex = 17;
        lblAddressCity.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAddressCity.Appearance.Options.UseFont = true;
        lblAddressCity.Location = new Point(318, 84);
        lblAddressCity.Name = "lblAddressCity";
        lblAddressCity.Size = new Size(83, 15);
        lblAddressCity.Text = "Ciudad / Distrito:";
        txtAddressCity.Location = new Point(410, 81);
        txtAddressCity.Name = "txtAddressCity";
        txtAddressCity.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        txtAddressCity.Properties.Appearance.Options.UseFont = true;
        txtAddressCity.Size = new Size(80, 22);
        txtAddressCity.TabIndex = 19;
        lblAddressCountry.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAddressCountry.Appearance.Options.UseFont = true;
        lblAddressCountry.Location = new Point(318, 114);
        lblAddressCountry.Name = "lblAddressCountry";
        lblAddressCountry.Size = new Size(25, 15);
        lblAddressCountry.Text = "País:";
        lueAddressCountry.Location = new Point(410, 111);
        lueAddressCountry.Name = "lueAddressCountry";
        lueAddressCountry.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueAddressCountry.Properties.Appearance.Options.UseFont = true;
        lueAddressCountry.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueAddressCountry.Properties.NullText = string.Empty;
        lueAddressCountry.Size = new Size(80, 22);
        lueAddressCountry.TabIndex = 21;
        lblPostalCode.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblPostalCode.Appearance.Options.UseFont = true;
        lblPostalCode.Location = new Point(318, 144);
        lblPostalCode.Name = "lblPostalCode";
        lblPostalCode.Size = new Size(73, 15);
        lblPostalCode.Text = "Código Postal:";
        txtPostalCode.Location = new Point(410, 141);
        txtPostalCode.Name = "txtPostalCode";
        txtPostalCode.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        txtPostalCode.Properties.Appearance.Options.UseFont = true;
        txtPostalCode.Size = new Size(80, 22);
        txtPostalCode.TabIndex = 23;
        lblLatitude.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblLatitude.Appearance.Options.UseFont = true;
        lblLatitude.Location = new Point(318, 174);
        lblLatitude.Name = "lblLatitude";
        lblLatitude.Size = new Size(40, 15);
        lblLatitude.Text = "Latitud:";
        spnLatitude.Location = new Point(410, 171);
        spnLatitude.Name = "spnLatitude";
        spnLatitude.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        spnLatitude.Properties.Appearance.Options.UseFont = true;
        spnLatitude.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        spnLatitude.Properties.DisplayFormat.FormatString = "n4";
        spnLatitude.Properties.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
        spnLatitude.Properties.EditFormat.FormatString = "n4";
        spnLatitude.Properties.EditFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
        spnLatitude.Properties.MaskSettings.Set("mask", "n4");
        spnLatitude.Size = new Size(80, 22);
        spnLatitude.TabIndex = 25;
        lblLongitude.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblLongitude.Appearance.Options.UseFont = true;
        lblLongitude.Location = new Point(318, 204);
        lblLongitude.Name = "lblLongitude";
        lblLongitude.Size = new Size(50, 15);
        lblLongitude.Text = "Longitud:";
        spnLongitude.Location = new Point(410, 201);
        spnLongitude.Name = "spnLongitude";
        spnLongitude.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        spnLongitude.Properties.Appearance.Options.UseFont = true;
        spnLongitude.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        spnLongitude.Properties.DisplayFormat.FormatString = "n4";
        spnLongitude.Properties.DisplayFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
        spnLongitude.Properties.EditFormat.FormatString = "n4";
        spnLongitude.Properties.EditFormat.FormatType = DevExpress.Utils.FormatType.Numeric;
        spnLongitude.Properties.MaskSettings.Set("mask", "n4");
        spnLongitude.Size = new Size(80, 22);
        spnLongitude.TabIndex = 27;
        lblDefaultDeliveryAddress.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblDefaultDeliveryAddress.Appearance.Options.UseFont = true;
        lblDefaultDeliveryAddress.Location = new Point(318, 234);
        lblDefaultDeliveryAddress.Name = "lblDefaultDeliveryAddress";
        lblDefaultDeliveryAddress.Size = new Size(87, 15);
        lblDefaultDeliveryAddress.Text = "Predet. Entrega:";
        tglDefaultDeliveryAddress.Location = new Point(410, 229);
        tglDefaultDeliveryAddress.Name = "tglDefaultDeliveryAddress";
        tglDefaultDeliveryAddress.Properties.OffText = string.Empty;
        tglDefaultDeliveryAddress.Properties.OnText = string.Empty;
        tglDefaultDeliveryAddress.Size = new Size(48, 24);
        tglDefaultDeliveryAddress.TabIndex = 29;
        lblDefaultDeliveryAddressValue.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblDefaultDeliveryAddressValue.Appearance.Options.UseFont = true;
        lblDefaultDeliveryAddressValue.Location = new Point(464, 234);
        lblDefaultDeliveryAddressValue.Name = "lblDefaultDeliveryAddressValue";
        lblDefaultDeliveryAddressValue.Size = new Size(11, 15);
        lblDefaultDeliveryAddressValue.Text = "Sí";
        lblAddressActive.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAddressActive.Appearance.Options.UseFont = true;
        lblAddressActive.Location = new Point(20, 234);
        lblAddressActive.Name = "lblAddressActive";
        lblAddressActive.Size = new Size(36, 15);
        lblAddressActive.Text = "Activa:";
        tglAddressActive.Location = new Point(146, 229);
        tglAddressActive.Name = "tglAddressActive";
        tglAddressActive.Properties.OffText = string.Empty;
        tglAddressActive.Properties.OnText = string.Empty;
        tglAddressActive.Size = new Size(48, 24);
        tglAddressActive.TabIndex = 32;
        lblAddressActiveValue.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAddressActiveValue.Appearance.Options.UseFont = true;
        lblAddressActiveValue.Location = new Point(200, 234);
        lblAddressActiveValue.Name = "lblAddressActiveValue";
        lblAddressActiveValue.Size = new Size(11, 15);
        lblAddressActiveValue.Text = "Sí";
        lblAddressNotes.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblAddressNotes.Appearance.Options.UseFont = true;
        lblAddressNotes.Location = new Point(20, 264);
        lblAddressNotes.Name = "lblAddressNotes";
        lblAddressNotes.Size = new Size(79, 15);
        lblAddressNotes.Text = "Observaciones:";
        memAddressNotes.Location = new Point(146, 261);
        memAddressNotes.Name = "memAddressNotes";
        memAddressNotes.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        memAddressNotes.Properties.Appearance.Options.UseFont = true;
        memAddressNotes.Size = new Size(344, 58);
        memAddressNotes.TabIndex = 35;
        // 
        // pnlFooter
        // 
        pnlFooter.BorderStyle = BorderStyles.NoBorder;
        pnlFooter.Controls.Add(btnSaveAddress);
        pnlFooter.Controls.Add(btnCancelAddress);
        pnlFooter.Dock = DockStyle.Bottom;
        pnlFooter.Location = new Point(0, 336);
        pnlFooter.Name = "pnlFooter";
        pnlFooter.Size = new Size(510, 64);
        pnlFooter.TabIndex = 1;
        // 
        // btnSaveAddress
        // 
        btnSaveAddress.Appearance.BackColor = Color.FromArgb(0, 102, 204);
        btnSaveAddress.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        btnSaveAddress.Appearance.ForeColor = Color.White;
        btnSaveAddress.Appearance.Options.UseBackColor = true;
        btnSaveAddress.Appearance.Options.UseFont = true;
        btnSaveAddress.Appearance.Options.UseForeColor = true;
        btnSaveAddress.Location = new Point(262, 16);
        btnSaveAddress.LookAndFeel.Style = DevExpress.LookAndFeel.LookAndFeelStyle.Flat;
        btnSaveAddress.LookAndFeel.UseDefaultLookAndFeel = false;
        btnSaveAddress.Name = "btnSaveAddress";
        btnSaveAddress.Size = new Size(100, 32);
        btnSaveAddress.TabIndex = 0;
        btnSaveAddress.Text = "Guardar";
        // 
        // btnCancelAddress
        // 
        btnCancelAddress.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        btnCancelAddress.Appearance.Options.UseFont = true;
        btnCancelAddress.DialogResult = DialogResult.Cancel;
        btnCancelAddress.Location = new Point(376, 16);
        btnCancelAddress.Name = "btnCancelAddress";
        btnCancelAddress.Size = new Size(100, 32);
        btnCancelAddress.TabIndex = 1;
        btnCancelAddress.Text = "Cancelar";
        // 
        // SupplierAddressEditDialog
        // 
        AcceptButton = btnSaveAddress;
        Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        Appearance.Options.UseFont = true;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        CancelButton = btnCancelAddress;
        ClientSize = new Size(510, 400);
        Controls.Add(pnlMain);
        Controls.Add(pnlFooter);
        Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "SupplierAddressEditDialog";
        ShowInTaskbar = false;
        StartPosition = FormStartPosition.CenterParent;
        Text = "Nueva Dirección";
        ((System.ComponentModel.ISupportInitialize)pnlMain).EndInit();
        pnlMain.ResumeLayout(false);
        pnlMain.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)lueAddressType.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtAddressName.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtMainStreet.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtSecondaryStreet.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtAddressNumber.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtAddressReference.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tglDefaultBillingAddress.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtNeighborhood.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtAddressProvince.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtAddressCity.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueAddressCountry.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtPostalCode.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)spnLatitude.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)spnLongitude.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tglDefaultDeliveryAddress.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tglAddressActive.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)memAddressNotes.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)pnlFooter).EndInit();
        pnlFooter.ResumeLayout(false);
        ResumeLayout(false);
    }

    private PanelControl pnlMain;
    private LabelControl lblAddressType;
    private LookUpEdit lueAddressType;
    private LabelControl lblAddressName;
    private TextEdit txtAddressName;
    private LabelControl lblMainStreet;
    private TextEdit txtMainStreet;
    private LabelControl lblSecondaryStreet;
    private TextEdit txtSecondaryStreet;
    private LabelControl lblAddressNumber;
    private TextEdit txtAddressNumber;
    private LabelControl lblAddressReference;
    private TextEdit txtAddressReference;
    private LabelControl lblDefaultBillingAddress;
    private ToggleSwitch tglDefaultBillingAddress;
    private LabelControl lblDefaultBillingAddressValue;
    private LabelControl lblNeighborhood;
    private TextEdit txtNeighborhood;
    private LabelControl lblAddressProvince;
    private TextEdit txtAddressProvince;
    private LabelControl lblAddressCity;
    private TextEdit txtAddressCity;
    private LabelControl lblAddressCountry;
    private LookUpEdit lueAddressCountry;
    private LabelControl lblPostalCode;
    private TextEdit txtPostalCode;
    private LabelControl lblLatitude;
    private SpinEdit spnLatitude;
    private LabelControl lblLongitude;
    private SpinEdit spnLongitude;
    private LabelControl lblDefaultDeliveryAddress;
    private ToggleSwitch tglDefaultDeliveryAddress;
    private LabelControl lblDefaultDeliveryAddressValue;
    private LabelControl lblAddressActive;
    private ToggleSwitch tglAddressActive;
    private LabelControl lblAddressActiveValue;
    private LabelControl lblAddressNotes;
    private MemoEdit memAddressNotes;
    private PanelControl pnlFooter;
    private SimpleButton btnSaveAddress;
    private SimpleButton btnCancelAddress;
}
