using System.Drawing;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;

namespace NuanSystem.WinForms.Forms.BusinessPartners;

partial class SupplierWithholdingEditDialog
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        pnlMain = new PanelControl();
        lblWithholdingDocument = new LabelControl();
        txtWithholdingDocument = new TextEdit();
        lblWithholdingType = new LabelControl();
        lueWithholdingType = new LookUpEdit();
        lblIncomeTaxWithholdingPercent = new LabelControl();
        spnIncomeTaxWithholdingPercent = new SpinEdit();
        lblVatWithholdingPercent = new LabelControl();
        spnVatWithholdingPercent = new SpinEdit();
        lblTaxSupport = new LabelControl();
        lueTaxSupport = new LookUpEdit();
        lblFiscalRegime = new LabelControl();
        lueFiscalRegime = new LookUpEdit();
        lblSpecialTaxpayer = new LabelControl();
        tglSpecialTaxpayer = new ToggleSwitch();
        lblSpecialTaxpayerValue = new LabelControl();
        lblRequiredAccounting = new LabelControl();
        tglRequiredAccounting = new ToggleSwitch();
        lblRequiredAccountingValue = new LabelControl();
        lblValidityFrom = new LabelControl();
        dteValidityFrom = new DateEdit();
        lblValidityTo = new LabelControl();
        dteValidityTo = new DateEdit();
        lblWithholdingDefault = new LabelControl();
        tglWithholdingDefault = new ToggleSwitch();
        lblWithholdingDefaultValue = new LabelControl();
        lblWithholdingActive = new LabelControl();
        tglWithholdingActive = new ToggleSwitch();
        lblWithholdingActiveValue = new LabelControl();
        lblWithholdingNotes = new LabelControl();
        memWithholdingNotes = new MemoEdit();
        pnlFooter = new PanelControl();
        btnSaveWithholding = new SimpleButton();
        btnCancelWithholding = new SimpleButton();
        ((System.ComponentModel.ISupportInitialize)pnlMain).BeginInit();
        pnlMain.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)txtWithholdingDocument.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueWithholdingType.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)spnIncomeTaxWithholdingPercent.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)spnVatWithholdingPercent.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueTaxSupport.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueFiscalRegime.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tglSpecialTaxpayer.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tglRequiredAccounting.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dteValidityFrom.Properties.CalendarTimeProperties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dteValidityFrom.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dteValidityTo.Properties.CalendarTimeProperties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)dteValidityTo.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tglWithholdingDefault.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tglWithholdingActive.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)memWithholdingNotes.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)pnlFooter).BeginInit();
        pnlFooter.SuspendLayout();
        SuspendLayout();
        // 
        // pnlMain
        // 
        pnlMain.BorderStyle = BorderStyles.NoBorder;
        pnlMain.Controls.Add(lblWithholdingDocument);
        pnlMain.Controls.Add(txtWithholdingDocument);
        pnlMain.Controls.Add(lblWithholdingType);
        pnlMain.Controls.Add(lueWithholdingType);
        pnlMain.Controls.Add(lblIncomeTaxWithholdingPercent);
        pnlMain.Controls.Add(spnIncomeTaxWithholdingPercent);
        pnlMain.Controls.Add(lblVatWithholdingPercent);
        pnlMain.Controls.Add(spnVatWithholdingPercent);
        pnlMain.Controls.Add(lblTaxSupport);
        pnlMain.Controls.Add(lueTaxSupport);
        pnlMain.Controls.Add(lblFiscalRegime);
        pnlMain.Controls.Add(lueFiscalRegime);
        pnlMain.Controls.Add(lblSpecialTaxpayer);
        pnlMain.Controls.Add(tglSpecialTaxpayer);
        pnlMain.Controls.Add(lblSpecialTaxpayerValue);
        pnlMain.Controls.Add(lblRequiredAccounting);
        pnlMain.Controls.Add(tglRequiredAccounting);
        pnlMain.Controls.Add(lblRequiredAccountingValue);
        pnlMain.Controls.Add(lblValidityFrom);
        pnlMain.Controls.Add(dteValidityFrom);
        pnlMain.Controls.Add(lblValidityTo);
        pnlMain.Controls.Add(dteValidityTo);
        pnlMain.Controls.Add(lblWithholdingDefault);
        pnlMain.Controls.Add(tglWithholdingDefault);
        pnlMain.Controls.Add(lblWithholdingDefaultValue);
        pnlMain.Controls.Add(lblWithholdingActive);
        pnlMain.Controls.Add(tglWithholdingActive);
        pnlMain.Controls.Add(lblWithholdingActiveValue);
        pnlMain.Controls.Add(lblWithholdingNotes);
        pnlMain.Controls.Add(memWithholdingNotes);
        pnlMain.Dock = DockStyle.Fill;
        pnlMain.Location = new Point(0, 0);
        pnlMain.Name = "pnlMain";
        pnlMain.Size = new Size(466, 410);
        pnlMain.TabIndex = 0;
        lblWithholdingDocument.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblWithholdingDocument.Appearance.Options.UseFont = true;
        lblWithholdingDocument.Location = new Point(22, 24);
        lblWithholdingDocument.Name = "lblWithholdingDocument";
        lblWithholdingDocument.Text = "Documento:";
        txtWithholdingDocument.Location = new Point(202, 21);
        txtWithholdingDocument.Name = "txtWithholdingDocument";
        txtWithholdingDocument.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        txtWithholdingDocument.Properties.Appearance.Options.UseFont = true;
        txtWithholdingDocument.Size = new Size(230, 22);
        txtWithholdingDocument.TabIndex = 1;
        lblWithholdingType.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblWithholdingType.Appearance.Options.UseFont = true;
        lblWithholdingType.Location = new Point(22, 52);
        lblWithholdingType.Name = "lblWithholdingType";
        lblWithholdingType.Text = "Tipo:";
        lueWithholdingType.Location = new Point(202, 49);
        lueWithholdingType.Name = "lueWithholdingType";
        lueWithholdingType.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueWithholdingType.Properties.Appearance.Options.UseFont = true;
        lueWithholdingType.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueWithholdingType.Properties.NullText = string.Empty;
        lueWithholdingType.Size = new Size(230, 22);
        lueWithholdingType.TabIndex = 3;
        lblIncomeTaxWithholdingPercent.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblIncomeTaxWithholdingPercent.Appearance.Options.UseFont = true;
        lblIncomeTaxWithholdingPercent.Location = new Point(22, 80);
        lblIncomeTaxWithholdingPercent.Name = "lblIncomeTaxWithholdingPercent";
        lblIncomeTaxWithholdingPercent.Text = "Porcentaje Retención Renta (%):";
        spnIncomeTaxWithholdingPercent.EditValue = new decimal(new int[] { 0, 0, 0, 0 });
        spnIncomeTaxWithholdingPercent.Location = new Point(202, 77);
        spnIncomeTaxWithholdingPercent.Name = "spnIncomeTaxWithholdingPercent";
        spnIncomeTaxWithholdingPercent.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        spnIncomeTaxWithholdingPercent.Properties.Appearance.Options.UseFont = true;
        spnIncomeTaxWithholdingPercent.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        spnIncomeTaxWithholdingPercent.Properties.MaskSettings.Set("mask", "n2");
        spnIncomeTaxWithholdingPercent.Size = new Size(110, 22);
        spnIncomeTaxWithholdingPercent.TabIndex = 5;
        lblVatWithholdingPercent.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblVatWithholdingPercent.Appearance.Options.UseFont = true;
        lblVatWithholdingPercent.Location = new Point(22, 108);
        lblVatWithholdingPercent.Name = "lblVatWithholdingPercent";
        lblVatWithholdingPercent.Text = "Porcentaje Retención IVA (%):";
        spnVatWithholdingPercent.EditValue = new decimal(new int[] { 0, 0, 0, 0 });
        spnVatWithholdingPercent.Location = new Point(202, 105);
        spnVatWithholdingPercent.Name = "spnVatWithholdingPercent";
        spnVatWithholdingPercent.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        spnVatWithholdingPercent.Properties.Appearance.Options.UseFont = true;
        spnVatWithholdingPercent.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        spnVatWithholdingPercent.Properties.MaskSettings.Set("mask", "n2");
        spnVatWithholdingPercent.Size = new Size(110, 22);
        spnVatWithholdingPercent.TabIndex = 7;
        lblTaxSupport.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblTaxSupport.Appearance.Options.UseFont = true;
        lblTaxSupport.Location = new Point(22, 136);
        lblTaxSupport.Name = "lblTaxSupport";
        lblTaxSupport.Text = "Sustento Tributario:";
        lueTaxSupport.Location = new Point(202, 133);
        lueTaxSupport.Name = "lueTaxSupport";
        lueTaxSupport.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueTaxSupport.Properties.Appearance.Options.UseFont = true;
        lueTaxSupport.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueTaxSupport.Properties.NullText = string.Empty;
        lueTaxSupport.Size = new Size(230, 22);
        lueTaxSupport.TabIndex = 9;
        lblFiscalRegime.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblFiscalRegime.Appearance.Options.UseFont = true;
        lblFiscalRegime.Location = new Point(22, 164);
        lblFiscalRegime.Name = "lblFiscalRegime";
        lblFiscalRegime.Text = "Régimen Fiscal:";
        lueFiscalRegime.Location = new Point(202, 161);
        lueFiscalRegime.Name = "lueFiscalRegime";
        lueFiscalRegime.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lueFiscalRegime.Properties.Appearance.Options.UseFont = true;
        lueFiscalRegime.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueFiscalRegime.Properties.NullText = string.Empty;
        lueFiscalRegime.Size = new Size(230, 22);
        lueFiscalRegime.TabIndex = 11;
        lblSpecialTaxpayer.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblSpecialTaxpayer.Appearance.Options.UseFont = true;
        lblSpecialTaxpayer.Location = new Point(22, 192);
        lblSpecialTaxpayer.Name = "lblSpecialTaxpayer";
        lblSpecialTaxpayer.Text = "Contribuyente Especial:";
        tglSpecialTaxpayer.Location = new Point(202, 187);
        tglSpecialTaxpayer.Name = "tglSpecialTaxpayer";
        tglSpecialTaxpayer.Properties.OffText = string.Empty;
        tglSpecialTaxpayer.Properties.OnText = string.Empty;
        tglSpecialTaxpayer.Size = new Size(50, 24);
        tglSpecialTaxpayer.TabIndex = 13;
        lblSpecialTaxpayerValue.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblSpecialTaxpayerValue.Appearance.Options.UseFont = true;
        lblSpecialTaxpayerValue.Location = new Point(258, 192);
        lblSpecialTaxpayerValue.Name = "lblSpecialTaxpayerValue";
        lblSpecialTaxpayerValue.Text = "No";
        lblRequiredAccounting.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblRequiredAccounting.Appearance.Options.UseFont = true;
        lblRequiredAccounting.Location = new Point(22, 220);
        lblRequiredAccounting.Name = "lblRequiredAccounting";
        lblRequiredAccounting.Text = "Obligado a llevar Contabilidad:";
        tglRequiredAccounting.Location = new Point(202, 215);
        tglRequiredAccounting.Name = "tglRequiredAccounting";
        tglRequiredAccounting.Properties.OffText = string.Empty;
        tglRequiredAccounting.Properties.OnText = string.Empty;
        tglRequiredAccounting.Size = new Size(50, 24);
        tglRequiredAccounting.TabIndex = 16;
        lblRequiredAccountingValue.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblRequiredAccountingValue.Appearance.Options.UseFont = true;
        lblRequiredAccountingValue.Location = new Point(258, 220);
        lblRequiredAccountingValue.Name = "lblRequiredAccountingValue";
        lblRequiredAccountingValue.Text = "Sí";
        lblValidityFrom.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblValidityFrom.Appearance.Options.UseFont = true;
        lblValidityFrom.Location = new Point(22, 248);
        lblValidityFrom.Name = "lblValidityFrom";
        lblValidityFrom.Text = "Vigencia Desde:";
        dteValidityFrom.Location = new Point(202, 245);
        dteValidityFrom.Name = "dteValidityFrom";
        dteValidityFrom.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        dteValidityFrom.Properties.Appearance.Options.UseFont = true;
        dteValidityFrom.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        dteValidityFrom.Properties.CalendarTimeProperties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        dteValidityFrom.Size = new Size(130, 22);
        dteValidityFrom.TabIndex = 19;
        lblValidityTo.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblValidityTo.Appearance.Options.UseFont = true;
        lblValidityTo.Location = new Point(22, 276);
        lblValidityTo.Name = "lblValidityTo";
        lblValidityTo.Text = "Vigencia Hasta:";
        dteValidityTo.Location = new Point(202, 273);
        dteValidityTo.Name = "dteValidityTo";
        dteValidityTo.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        dteValidityTo.Properties.Appearance.Options.UseFont = true;
        dteValidityTo.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        dteValidityTo.Properties.CalendarTimeProperties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        dteValidityTo.Size = new Size(130, 22);
        dteValidityTo.TabIndex = 21;
        lblWithholdingDefault.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblWithholdingDefault.Appearance.Options.UseFont = true;
        lblWithholdingDefault.Location = new Point(22, 304);
        lblWithholdingDefault.Name = "lblWithholdingDefault";
        lblWithholdingDefault.Text = "Predeterminado:";
        tglWithholdingDefault.Location = new Point(202, 299);
        tglWithholdingDefault.Name = "tglWithholdingDefault";
        tglWithholdingDefault.Properties.OffText = string.Empty;
        tglWithholdingDefault.Properties.OnText = string.Empty;
        tglWithholdingDefault.Size = new Size(50, 24);
        tglWithholdingDefault.TabIndex = 23;
        lblWithholdingDefaultValue.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblWithholdingDefaultValue.Appearance.Options.UseFont = true;
        lblWithholdingDefaultValue.Location = new Point(258, 304);
        lblWithholdingDefaultValue.Name = "lblWithholdingDefaultValue";
        lblWithholdingDefaultValue.Text = "Sí";
        lblWithholdingActive.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblWithholdingActive.Appearance.Options.UseFont = true;
        lblWithholdingActive.Location = new Point(22, 332);
        lblWithholdingActive.Name = "lblWithholdingActive";
        lblWithholdingActive.Text = "Activo:";
        tglWithholdingActive.Location = new Point(202, 327);
        tglWithholdingActive.Name = "tglWithholdingActive";
        tglWithholdingActive.Properties.OffText = string.Empty;
        tglWithholdingActive.Properties.OnText = string.Empty;
        tglWithholdingActive.Size = new Size(50, 24);
        tglWithholdingActive.TabIndex = 26;
        lblWithholdingActiveValue.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblWithholdingActiveValue.Appearance.Options.UseFont = true;
        lblWithholdingActiveValue.Location = new Point(258, 332);
        lblWithholdingActiveValue.Name = "lblWithholdingActiveValue";
        lblWithholdingActiveValue.Text = "Sí";
        lblWithholdingNotes.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        lblWithholdingNotes.Appearance.Options.UseFont = true;
        lblWithholdingNotes.Location = new Point(22, 360);
        lblWithholdingNotes.Name = "lblWithholdingNotes";
        lblWithholdingNotes.Text = "Observaciones:";
        memWithholdingNotes.Location = new Point(202, 357);
        memWithholdingNotes.Name = "memWithholdingNotes";
        memWithholdingNotes.Properties.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        memWithholdingNotes.Properties.Appearance.Options.UseFont = true;
        memWithholdingNotes.Size = new Size(230, 42);
        memWithholdingNotes.TabIndex = 29;
        // 
        // pnlFooter
        // 
        pnlFooter.BorderStyle = BorderStyles.NoBorder;
        pnlFooter.Controls.Add(btnSaveWithholding);
        pnlFooter.Controls.Add(btnCancelWithholding);
        pnlFooter.Dock = DockStyle.Bottom;
        pnlFooter.Location = new Point(0, 410);
        pnlFooter.Name = "pnlFooter";
        pnlFooter.Size = new Size(466, 58);
        pnlFooter.TabIndex = 1;
        btnSaveWithholding.Appearance.BackColor = Color.FromArgb(0, 102, 204);
        btnSaveWithholding.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        btnSaveWithholding.Appearance.ForeColor = Color.White;
        btnSaveWithholding.Appearance.Options.UseBackColor = true;
        btnSaveWithholding.Appearance.Options.UseFont = true;
        btnSaveWithholding.Appearance.Options.UseForeColor = true;
        btnSaveWithholding.Location = new Point(160, 12);
        btnSaveWithholding.Name = "btnSaveWithholding";
        btnSaveWithholding.Size = new Size(108, 32);
        btnSaveWithholding.TabIndex = 0;
        btnSaveWithholding.Text = "Guardar";
        btnCancelWithholding.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold, GraphicsUnit.Point);
        btnCancelWithholding.Appearance.Options.UseFont = true;
        btnCancelWithholding.DialogResult = DialogResult.Cancel;
        btnCancelWithholding.Location = new Point(282, 12);
        btnCancelWithholding.Name = "btnCancelWithholding";
        btnCancelWithholding.Size = new Size(108, 32);
        btnCancelWithholding.TabIndex = 1;
        btnCancelWithholding.Text = "Cancelar";
        // 
        // SupplierWithholdingEditDialog
        // 
        AcceptButton = btnSaveWithholding;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        CancelButton = btnCancelWithholding;
        ClientSize = new Size(466, 468);
        Controls.Add(pnlMain);
        Controls.Add(pnlFooter);
        Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "SupplierWithholdingEditDialog";
        ShowInTaskbar = false;
        StartPosition = FormStartPosition.CenterParent;
        Text = "Nueva Configuración de Retención";
        ((System.ComponentModel.ISupportInitialize)pnlMain).EndInit();
        pnlMain.ResumeLayout(false);
        pnlMain.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)txtWithholdingDocument.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueWithholdingType.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)spnIncomeTaxWithholdingPercent.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)spnVatWithholdingPercent.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueTaxSupport.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueFiscalRegime.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tglSpecialTaxpayer.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tglRequiredAccounting.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)dteValidityFrom.Properties.CalendarTimeProperties).EndInit();
        ((System.ComponentModel.ISupportInitialize)dteValidityFrom.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)dteValidityTo.Properties.CalendarTimeProperties).EndInit();
        ((System.ComponentModel.ISupportInitialize)dteValidityTo.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tglWithholdingDefault.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tglWithholdingActive.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)memWithholdingNotes.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)pnlFooter).EndInit();
        pnlFooter.ResumeLayout(false);
        ResumeLayout(false);
    }

    private PanelControl pnlMain;
    private LabelControl lblWithholdingDocument;
    private TextEdit txtWithholdingDocument;
    private LabelControl lblWithholdingType;
    private LookUpEdit lueWithholdingType;
    private LabelControl lblIncomeTaxWithholdingPercent;
    private SpinEdit spnIncomeTaxWithholdingPercent;
    private LabelControl lblVatWithholdingPercent;
    private SpinEdit spnVatWithholdingPercent;
    private LabelControl lblTaxSupport;
    private LookUpEdit lueTaxSupport;
    private LabelControl lblFiscalRegime;
    private LookUpEdit lueFiscalRegime;
    private LabelControl lblSpecialTaxpayer;
    private ToggleSwitch tglSpecialTaxpayer;
    private LabelControl lblSpecialTaxpayerValue;
    private LabelControl lblRequiredAccounting;
    private ToggleSwitch tglRequiredAccounting;
    private LabelControl lblRequiredAccountingValue;
    private LabelControl lblValidityFrom;
    private DateEdit dteValidityFrom;
    private LabelControl lblValidityTo;
    private DateEdit dteValidityTo;
    private LabelControl lblWithholdingDefault;
    private ToggleSwitch tglWithholdingDefault;
    private LabelControl lblWithholdingDefaultValue;
    private LabelControl lblWithholdingActive;
    private ToggleSwitch tglWithholdingActive;
    private LabelControl lblWithholdingActiveValue;
    private LabelControl lblWithholdingNotes;
    private MemoEdit memWithholdingNotes;
    private PanelControl pnlFooter;
    private SimpleButton btnSaveWithholding;
    private SimpleButton btnCancelWithholding;
}
