using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using NuanSystem.WinForms.Controls.Editors;
using NuanSystem.WinForms.Forms.Common;

namespace NuanSystem.WinForms.Forms.Definitions.Inventory.ItemAlertTypes;

partial class ItemAlertTypeEditForm
{
    private System.ComponentModel.IContainer components = null;
    private LabelControl lblCode;
    private TextEdit txtCode;
    private LabelControl lblName;
    private TextEdit txtName;
    private LabelControl lblDescription;
    private MemoEdit memDescription;
    private LabelControl lblSortOrder;
    private SpinEdit spnSortOrder;
    private LabelControl lblIsActive;
    private NuanToggleSwitch tglIsActive;
    private void InitializeComponent()
    {
        lblCode = new LabelControl();
        txtCode = new TextEdit();
        lblName = new LabelControl();
        txtName = new TextEdit();
        lblDescription = new LabelControl();
        memDescription = new MemoEdit();
        lblSortOrder = new LabelControl();
        spnSortOrder = new SpinEdit();
        lblIsActive = new LabelControl();
        tglIsActive = new NuanToggleSwitch();
        ((System.ComponentModel.ISupportInitialize)txtCode.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtName.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)memDescription.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)spnSortOrder.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)tglIsActive.Properties).BeginInit();
        SuspendLayout();
        lblCode.Appearance.Font = new Font("Segoe UI", 9F);
        lblCode.Appearance.ForeColor = BrandResources.Text;
        lblCode.Appearance.Options.UseFont = true;
        lblCode.Appearance.Options.UseForeColor = true;
        lblCode.Location = new Point(32, 29);
        lblCode.Name = "lblCode";
        lblCode.Text = "Código:";
        txtCode.Location = new Point(154, 26);
        txtCode.Name = "txtCode";
        txtCode.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        txtCode.Properties.Appearance.Options.UseFont = true;
        txtCode.Size = new Size(180, 22);
        txtCode.TabIndex = 0;
        txtCode.Properties.AutoHeight = false;
        lblName.Appearance.Font = new Font("Segoe UI", 9F);
        lblName.Appearance.ForeColor = BrandResources.Text;
        lblName.Appearance.Options.UseFont = true;
        lblName.Appearance.Options.UseForeColor = true;
        lblName.Location = new Point(32, 57);
        lblName.Name = "lblName";
        lblName.Text = "Nombre:";
        txtName.Location = new Point(154, 54);
        txtName.Name = "txtName";
        txtName.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        txtName.Properties.Appearance.Options.UseFont = true;
        txtName.Size = new Size(436, 22);
        txtName.TabIndex = 2;
        txtName.Properties.AutoHeight = false;
        lblDescription.Appearance.Font = new Font("Segoe UI", 9F);
        lblDescription.Appearance.ForeColor = BrandResources.Text;
        lblDescription.Appearance.Options.UseFont = true;
        lblDescription.Appearance.Options.UseForeColor = true;
        lblDescription.Location = new Point(32, 85);
        lblDescription.Name = "lblDescription";
        lblDescription.Text = "Descripción:";
        memDescription.Location = new Point(154, 82);
        memDescription.Name = "memDescription";
        memDescription.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        memDescription.Properties.Appearance.Options.UseFont = true;
        memDescription.Size = new Size(436, 64);
        memDescription.TabIndex = 4;
        lblSortOrder.Appearance.Font = new Font("Segoe UI", 9F);
        lblSortOrder.Appearance.ForeColor = BrandResources.Text;
        lblSortOrder.Appearance.Options.UseFont = true;
        lblSortOrder.Appearance.Options.UseForeColor = true;
        lblSortOrder.Location = new Point(632, 29);
        lblSortOrder.Name = "lblSortOrder";
        lblSortOrder.Text = "Orden:";
        spnSortOrder.Location = new Point(680, 26);
        spnSortOrder.Name = "spnSortOrder";
        spnSortOrder.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        spnSortOrder.Properties.Appearance.Options.UseFont = true;
        spnSortOrder.Size = new Size(150, 22);
        spnSortOrder.TabIndex = 1;
        spnSortOrder.Properties.AutoHeight = false;
        lblIsActive.Appearance.Font = new Font("Segoe UI", 9F);
        lblIsActive.Appearance.ForeColor = BrandResources.Text;
        lblIsActive.Appearance.Options.UseFont = true;
        lblIsActive.Appearance.Options.UseForeColor = true;
        lblIsActive.Location = new Point(632, 57);
        lblIsActive.Name = "lblIsActive";
        lblIsActive.Text = "Activo:";
        tglIsActive.Location = new Point(684, 54);
        tglIsActive.Name = "tglIsActive";
        tglIsActive.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        tglIsActive.Properties.Appearance.Options.UseFont = true;
        tglIsActive.Size = new Size(120, 20);
        tglIsActive.TabIndex = 3;
        tglIsActive.ActiveColor = BrandResources.Primary;
        tglIsActive.InactiveColor = BrandResources.Border;
        tglIsActive.Properties.OnText = "Sí";
        tglIsActive.Properties.OffText = "No";
        Appearance.BackColor = Color.White;
        Appearance.Options.UseBackColor = true;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(870, 202);
        CancelButtonLocation = new Point(628, 156);
        SaveButtonLocation = new Point(734, 156);
        Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
        Controls.Add(lblCode);
        Controls.Add(txtCode);
        Controls.Add(lblName);
        Controls.Add(txtName);
        Controls.Add(lblDescription);
        Controls.Add(memDescription);
        Controls.Add(lblSortOrder);
        Controls.Add(spnSortOrder);
        Controls.Add(lblIsActive);
        Controls.Add(tglIsActive);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        MinimumSize = new Size(886, 241);
        Name = "ItemAlertTypeEditForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "Tipos de alerta de artículos";
        ((System.ComponentModel.ISupportInitialize)txtCode.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtName.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)memDescription.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)spnSortOrder.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)tglIsActive.Properties).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }
    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }
}

