namespace NuanSystem.Application.Features.GeneralInventory.ItemGroups.Dtos;

public sealed record CreateItemGroupData(
    Guid GlobalId,
    string Code,
    string Name,
    string? Description,
    string? ExternalSystem,
    string? ExternalCode,
    bool IsActive,
    string? InventoryAccountCode,
    string? IncomeAccountCode,
    string? CostOfSalesAccountCode,
    string? SalesReturnAccountCode,
    string? PurchaseReturnAccountCode,
    string? CostVarianceAccountCode,
    string? InventoryAdjustmentAccountCode,
    string? PurchaseExpenseAccountCode,
    int SortOrder,
    string? SalesAccountCode,
    string? PurchaseAccountCode,
    string? SapGroupCode,
    string? SapCode,
    int? CreatedByUserId,
    string? CreatedByUserName);
