using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraTreeList;
using DevExpress.XtraTreeList.Columns;
using NuanSystem.WinForms.Forms.Common;

namespace NuanSystem.WinForms.Forms.Accounting.ChartOfAccounts;

partial class ChartOfAccountEditForm
{
    private System.ComponentModel.IContainer components = null;

    private void InitializeComponent()
    {
        lblTitulo = new LabelControl();
        lblCodigo = new LabelControl();
        txtCodigo = new TextEdit();
        lblNombre = new LabelControl();
        txtNombre = new TextEdit();
        lblDescripcion = new LabelControl();
        memDescripcion = new MemoEdit();
        lblCodigoExterno = new LabelControl();
        txtCodigoExterno = new TextEdit();
        lblTipoCuenta = new LabelControl();
        lueTipoCuenta = new LookUpEdit();
        lblClaseCuenta = new LabelControl();
        lueClaseCuenta = new LookUpEdit();
        lblCuentaPadre = new LabelControl();
        lueCuentaPadre = new LookUpEdit();
        lblMoneda = new LabelControl();
        txtMoneda = new TextEdit();
        lblSaldo = new LabelControl();
        txtSaldo = new TextEdit();
        lblNivel = new LabelControl();
        txtNivel = new TextEdit();
        chkTitulo = new CheckEdit();
        chkPermiteMovimiento = new CheckEdit();
        chkConfidencial = new CheckEdit();
        chkCuentaMonetaria = new CheckEdit();
        chkCuentaAsociada = new CheckEdit();
        chkRevaluaIndice = new CheckEdit();
        chkBloquearManual = new CheckEdit();
        chkFlujoCaja = new CheckEdit();
        chkCentroCosto = new CheckEdit();
        chkTercero = new CheckEdit();
        chkProyecto = new CheckEdit();
        chkActivo = new CheckEdit();
        trlAccounts = new TreeList();
        colAccountDisplay = new TreeListColumn();
        btnTipoActivo = new SimpleButton();
        btnTipoPasivo = new SimpleButton();
        btnTipoPatrimonio = new SimpleButton();
        btnTipoIngreso = new SimpleButton();
        btnTipoCosto = new SimpleButton();
        btnTipoGasto = new SimpleButton();
        btnTipoOrden = new SimpleButton();
        btnGuardar = new SimpleButton();
        btnCancelar = new SimpleButton();
        ((System.ComponentModel.ISupportInitialize)txtCodigo.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtNombre.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)memDescripcion.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtCodigoExterno.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueTipoCuenta.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueClaseCuenta.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueCuentaPadre.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtMoneda.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtSaldo.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtNivel.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkTitulo.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkPermiteMovimiento.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkConfidencial.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkCuentaMonetaria.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkCuentaAsociada.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkRevaluaIndice.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkBloquearManual.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkFlujoCaja.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkCentroCosto.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkTercero.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkProyecto.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkActivo.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)trlAccounts).BeginInit();
        SuspendLayout();
        lblTitulo.Appearance.Font = new Font("Segoe UI", 9F, FontStyle.Underline);
        lblTitulo.Appearance.Options.UseFont = true;
        lblTitulo.Location = new Point(18, 16);
        lblTitulo.Name = "lblTitulo";
        lblTitulo.Size = new Size(201, 15);
        lblTitulo.TabIndex = 0;
        lblTitulo.Text = "Info detallada de cuenta contable";
        lblCodigo.Location = new Point(18, 58);
        lblCodigo.Name = "lblCodigo";
        lblCodigo.Size = new Size(40, 15);
        lblCodigo.TabIndex = 1;
        lblCodigo.Text = "Codigo";
        txtCodigo.Location = new Point(178, 55);
        txtCodigo.Name = "txtCodigo";
        txtCodigo.Properties.MaxLength = 50;
        txtCodigo.Size = new Size(250, 22);
        txtCodigo.TabIndex = 2;
        lblNombre.Location = new Point(18, 86);
        lblNombre.Name = "lblNombre";
        lblNombre.Size = new Size(44, 15);
        lblNombre.TabIndex = 3;
        lblNombre.Text = "Nombre";
        txtNombre.Location = new Point(178, 83);
        txtNombre.Name = "txtNombre";
        txtNombre.Properties.MaxLength = 200;
        txtNombre.Size = new Size(250, 22);
        txtNombre.TabIndex = 4;
        lblDescripcion.Location = new Point(18, 114);
        lblDescripcion.Name = "lblDescripcion";
        lblDescripcion.Size = new Size(63, 15);
        lblDescripcion.TabIndex = 5;
        lblDescripcion.Text = "Descripcion";
        memDescripcion.Location = new Point(178, 111);
        memDescripcion.Name = "memDescripcion";
        memDescripcion.Properties.MaxLength = 500;
        memDescripcion.Size = new Size(250, 64);
        memDescripcion.TabIndex = 6;
        lblCodigoExterno.Location = new Point(18, 184);
        lblCodigoExterno.Name = "lblCodigoExterno";
        lblCodigoExterno.Size = new Size(82, 15);
        lblCodigoExterno.TabIndex = 7;
        lblCodigoExterno.Text = "Codigo externo";
        txtCodigoExterno.Location = new Point(178, 181);
        txtCodigoExterno.Name = "txtCodigoExterno";
        txtCodigoExterno.Properties.MaxLength = 50;
        txtCodigoExterno.Size = new Size(250, 22);
        txtCodigoExterno.TabIndex = 8;
        lblTipoCuenta.Location = new Point(18, 214);
        lblTipoCuenta.Name = "lblTipoCuenta";
        lblTipoCuenta.Size = new Size(80, 15);
        lblTipoCuenta.TabIndex = 9;
        lblTipoCuenta.Text = "Clase de cuenta";
        lueTipoCuenta.Location = new Point(178, 211);
        lueTipoCuenta.Name = "lueTipoCuenta";
        lueTipoCuenta.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueTipoCuenta.Size = new Size(250, 22);
        lueTipoCuenta.TabIndex = 10;
        lblClaseCuenta.Location = new Point(18, 244);
        lblClaseCuenta.Name = "lblClaseCuenta";
        lblClaseCuenta.Size = new Size(85, 15);
        lblClaseCuenta.TabIndex = 11;
        lblClaseCuenta.Text = "Propiedad cuenta";
        lueClaseCuenta.Location = new Point(178, 241);
        lueClaseCuenta.Name = "lueClaseCuenta";
        lueClaseCuenta.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueClaseCuenta.Size = new Size(250, 22);
        lueClaseCuenta.TabIndex = 12;
        lblCuentaPadre.Location = new Point(18, 274);
        lblCuentaPadre.Name = "lblCuentaPadre";
        lblCuentaPadre.Size = new Size(72, 15);
        lblCuentaPadre.TabIndex = 13;
        lblCuentaPadre.Text = "Cuenta padre";
        lueCuentaPadre.Location = new Point(178, 271);
        lueCuentaPadre.Name = "lueCuentaPadre";
        lueCuentaPadre.Properties.AllowNullInput = DevExpress.Utils.DefaultBoolean.True;
        lueCuentaPadre.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
        lueCuentaPadre.Size = new Size(250, 22);
        lueCuentaPadre.TabIndex = 14;
        lblMoneda.Location = new Point(18, 304);
        lblMoneda.Name = "lblMoneda";
        lblMoneda.Size = new Size(45, 15);
        lblMoneda.TabIndex = 15;
        lblMoneda.Text = "Moneda";
        txtMoneda.Location = new Point(178, 301);
        txtMoneda.Name = "txtMoneda";
        txtMoneda.Properties.MaxLength = 3;
        txtMoneda.Size = new Size(80, 22);
        txtMoneda.TabIndex = 16;
        lblSaldo.Location = new Point(18, 332);
        lblSaldo.Name = "lblSaldo";
        lblSaldo.Size = new Size(31, 15);
        lblSaldo.TabIndex = 17;
        lblSaldo.Text = "Saldo";
        txtSaldo.Location = new Point(178, 329);
        txtSaldo.Name = "txtSaldo";
        txtSaldo.Properties.MaskSettings.Set("MaskManagerType", typeof(DevExpress.Data.Mask.NumericMaskManager));
        txtSaldo.Properties.MaskSettings.Set("mask", "n2");
        txtSaldo.Size = new Size(120, 22);
        txtSaldo.TabIndex = 18;
        lblNivel.Location = new Point(318, 332);
        lblNivel.Name = "lblNivel";
        lblNivel.Size = new Size(25, 15);
        lblNivel.TabIndex = 19;
        lblNivel.Text = "Nivel";
        txtNivel.Location = new Point(374, 329);
        txtNivel.Name = "txtNivel";
        txtNivel.Properties.ReadOnly = true;
        txtNivel.Size = new Size(54, 22);
        txtNivel.TabIndex = 20;
        chkTitulo.Location = new Point(175, 362);
        chkTitulo.Name = "chkTitulo";
        chkTitulo.Properties.Caption = "Titulo / cuenta agrupadora";
        chkTitulo.Size = new Size(180, 22);
        chkTitulo.TabIndex = 21;
        chkPermiteMovimiento.Location = new Point(175, 388);
        chkPermiteMovimiento.Name = "chkPermiteMovimiento";
        chkPermiteMovimiento.Properties.Caption = "Permite movimientos";
        chkPermiteMovimiento.Size = new Size(230, 22);
        chkPermiteMovimiento.TabIndex = 22;
        chkConfidencial.Location = new Point(175, 414);
        chkConfidencial.Name = "chkConfidencial";
        chkConfidencial.Properties.Caption = "Confidencial";
        chkConfidencial.Size = new Size(110, 22);
        chkConfidencial.TabIndex = 23;
        chkCuentaMonetaria.Location = new Point(304, 414);
        chkCuentaMonetaria.Name = "chkCuentaMonetaria";
        chkCuentaMonetaria.Properties.Caption = "Cuenta monetaria";
        chkCuentaMonetaria.Size = new Size(130, 22);
        chkCuentaMonetaria.TabIndex = 24;
        chkCuentaAsociada.Location = new Point(175, 440);
        chkCuentaAsociada.Name = "chkCuentaAsociada";
        chkCuentaAsociada.Properties.Caption = "Cuenta asociada";
        chkCuentaAsociada.Size = new Size(120, 22);
        chkCuentaAsociada.TabIndex = 25;
        chkRevaluaIndice.Location = new Point(304, 440);
        chkRevaluaIndice.Name = "chkRevaluaIndice";
        chkRevaluaIndice.Properties.Caption = "Reval. segun indice";
        chkRevaluaIndice.Size = new Size(140, 22);
        chkRevaluaIndice.TabIndex = 26;
        chkBloquearManual.Location = new Point(175, 466);
        chkBloquearManual.Name = "chkBloquearManual";
        chkBloquearManual.Properties.Caption = "Bloquear contabilizacion manual";
        chkBloquearManual.Size = new Size(220, 22);
        chkBloquearManual.TabIndex = 27;
        chkFlujoCaja.Location = new Point(175, 492);
        chkFlujoCaja.Name = "chkFlujoCaja";
        chkFlujoCaja.Properties.Caption = "Relevante para flujo de caja";
        chkFlujoCaja.Size = new Size(190, 22);
        chkFlujoCaja.TabIndex = 28;
        chkCentroCosto.Location = new Point(175, 542);
        chkCentroCosto.Name = "chkCentroCosto";
        chkCentroCosto.Properties.Caption = "Centro de costo";
        chkCentroCosto.Size = new Size(120, 22);
        chkCentroCosto.TabIndex = 29;
        chkTercero.Location = new Point(304, 542);
        chkTercero.Name = "chkTercero";
        chkTercero.Properties.Caption = "Tercero";
        chkTercero.Size = new Size(90, 22);
        chkTercero.TabIndex = 30;
        chkProyecto.Location = new Point(175, 568);
        chkProyecto.Name = "chkProyecto";
        chkProyecto.Properties.Caption = "Proyecto";
        chkProyecto.Size = new Size(90, 22);
        chkProyecto.TabIndex = 31;
        chkActivo.Location = new Point(304, 568);
        chkActivo.Name = "chkActivo";
        chkActivo.Properties.Caption = "Activo";
        chkActivo.Size = new Size(80, 22);
        chkActivo.TabIndex = 32;
        trlAccounts.Columns.AddRange(new TreeListColumn[] { colAccountDisplay });
        trlAccounts.KeyFieldName = "Id";
        trlAccounts.Location = new Point(456, 56);
        trlAccounts.Name = "trlAccounts";
        trlAccounts.OptionsBehavior.Editable = false;
        trlAccounts.OptionsView.ShowColumns = false;
        trlAccounts.OptionsView.ShowHorzLines = false;
        trlAccounts.OptionsView.ShowIndicator = false;
        trlAccounts.OptionsView.ShowVertLines = false;
        trlAccounts.ParentFieldName = "ParentAccountId";
        trlAccounts.Size = new Size(500, 548);
        trlAccounts.TabIndex = 20;
        colAccountDisplay.Caption = "Cuenta";
        colAccountDisplay.FieldName = "DisplayText";
        colAccountDisplay.Name = "colAccountDisplay";
        colAccountDisplay.Visible = true;
        colAccountDisplay.VisibleIndex = 0;
        btnTipoActivo.Location = new Point(976, 56);
        btnTipoActivo.Name = "btnTipoActivo";
        btnTipoActivo.Size = new Size(130, 54);
        btnTipoActivo.TabIndex = 21;
        btnTipoActivo.Text = "Activos";
        btnTipoPasivo.Location = new Point(976, 116);
        btnTipoPasivo.Name = "btnTipoPasivo";
        btnTipoPasivo.Size = new Size(130, 54);
        btnTipoPasivo.TabIndex = 22;
        btnTipoPasivo.Text = "Pasivos";
        btnTipoPatrimonio.Location = new Point(976, 176);
        btnTipoPatrimonio.Name = "btnTipoPatrimonio";
        btnTipoPatrimonio.Size = new Size(130, 54);
        btnTipoPatrimonio.TabIndex = 23;
        btnTipoPatrimonio.Text = "Patrimonio";
        btnTipoIngreso.Location = new Point(976, 236);
        btnTipoIngreso.Name = "btnTipoIngreso";
        btnTipoIngreso.Size = new Size(130, 54);
        btnTipoIngreso.TabIndex = 24;
        btnTipoIngreso.Text = "Ingresos";
        btnTipoCosto.Location = new Point(976, 296);
        btnTipoCosto.Name = "btnTipoCosto";
        btnTipoCosto.Size = new Size(130, 54);
        btnTipoCosto.TabIndex = 25;
        btnTipoCosto.Text = "Costos";
        btnTipoGasto.Location = new Point(976, 356);
        btnTipoGasto.Name = "btnTipoGasto";
        btnTipoGasto.Size = new Size(130, 54);
        btnTipoGasto.TabIndex = 26;
        btnTipoGasto.Text = "Gastos";
        btnTipoOrden.Location = new Point(976, 416);
        btnTipoOrden.Name = "btnTipoOrden";
        btnTipoOrden.Size = new Size(130, 54);
        btnTipoOrden.TabIndex = 27;
        btnTipoOrden.Text = "Orden";
        btnGuardar.Appearance.BackColor = BrandResources.Primary;
        btnGuardar.Appearance.ForeColor = Color.White;
        btnGuardar.Appearance.Options.UseBackColor = true;
        btnGuardar.Appearance.Options.UseForeColor = true;
        btnGuardar.Location = new Point(1006, 625);
        btnGuardar.Name = "btnGuardar";
        btnGuardar.Size = new Size(100, 32);
        btnGuardar.TabIndex = 29;
        btnGuardar.Text = "Guardar";
        btnCancelar.DialogResult = DialogResult.Cancel;
        btnCancelar.Location = new Point(900, 625);
        btnCancelar.Name = "btnCancelar";
        btnCancelar.Size = new Size(100, 32);
        btnCancelar.TabIndex = 28;
        btnCancelar.Text = "Cancelar";
        AcceptButton = btnGuardar;
        Appearance.BackColor = BrandResources.Background;
        Appearance.Options.UseBackColor = true;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        CancelButton = btnCancelar;
        ClientSize = new Size(1124, 676);
        Controls.AddRange(new Control[] { lblTitulo, lblCodigo, txtCodigo, lblNombre, txtNombre, lblDescripcion, memDescripcion, lblCodigoExterno, txtCodigoExterno, lblTipoCuenta, lueTipoCuenta, lblClaseCuenta, lueClaseCuenta, lblCuentaPadre, lueCuentaPadre, lblMoneda, txtMoneda, lblSaldo, txtSaldo, lblNivel, txtNivel, chkTitulo, chkPermiteMovimiento, chkConfidencial, chkCuentaMonetaria, chkCuentaAsociada, chkRevaluaIndice, chkBloquearManual, chkFlujoCaja, chkCentroCosto, chkTercero, chkProyecto, chkActivo, trlAccounts, btnTipoActivo, btnTipoPasivo, btnTipoPatrimonio, btnTipoIngreso, btnTipoCosto, btnTipoGasto, btnTipoOrden, btnGuardar, btnCancelar });
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "ChartOfAccountEditForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "Plan de cuentas";
        ((System.ComponentModel.ISupportInitialize)txtCodigo.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtNombre.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)memDescripcion.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtCodigoExterno.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueTipoCuenta.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueClaseCuenta.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueCuentaPadre.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtMoneda.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtSaldo.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtNivel.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkTitulo.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkPermiteMovimiento.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkConfidencial.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkCuentaMonetaria.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkCuentaAsociada.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkRevaluaIndice.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkBloquearManual.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkFlujoCaja.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkCentroCosto.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkTercero.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkProyecto.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkActivo.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)trlAccounts).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    private LabelControl lblTitulo;
    private LabelControl lblCodigo;
    private TextEdit txtCodigo;
    private LabelControl lblNombre;
    private TextEdit txtNombre;
    private LabelControl lblDescripcion;
    private MemoEdit memDescripcion;
    private LabelControl lblCodigoExterno;
    private TextEdit txtCodigoExterno;
    private LabelControl lblTipoCuenta;
    private LookUpEdit lueTipoCuenta;
    private LabelControl lblClaseCuenta;
    private LookUpEdit lueClaseCuenta;
    private LabelControl lblCuentaPadre;
    private LookUpEdit lueCuentaPadre;
    private LabelControl lblMoneda;
    private TextEdit txtMoneda;
    private LabelControl lblSaldo;
    private TextEdit txtSaldo;
    private LabelControl lblNivel;
    private TextEdit txtNivel;
    private CheckEdit chkTitulo;
    private CheckEdit chkPermiteMovimiento;
    private CheckEdit chkConfidencial;
    private CheckEdit chkCuentaMonetaria;
    private CheckEdit chkCuentaAsociada;
    private CheckEdit chkRevaluaIndice;
    private CheckEdit chkBloquearManual;
    private CheckEdit chkFlujoCaja;
    private CheckEdit chkCentroCosto;
    private CheckEdit chkTercero;
    private CheckEdit chkProyecto;
    private CheckEdit chkActivo;
    private TreeList trlAccounts;
    private TreeListColumn colAccountDisplay;
    private SimpleButton btnTipoActivo;
    private SimpleButton btnTipoPasivo;
    private SimpleButton btnTipoPatrimonio;
    private SimpleButton btnTipoIngreso;
    private SimpleButton btnTipoCosto;
    private SimpleButton btnTipoGasto;
    private SimpleButton btnTipoOrden;
    private SimpleButton btnGuardar;
    private SimpleButton btnCancelar;
}
