<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Backend\NuanSystem.Shared\NuanSystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DevExpress.Data.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Data.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Data.Desktop.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Data.Desktop.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Drawing.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Drawing.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Utils.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Utils.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Utils.v25.2.UI">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Utils.v25.2.UI.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Images.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Images.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.Printing.v25.2.Core">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.Printing.v25.2.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.XtraEditors.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.XtraEditors.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="DevExpress.XtraGrid.v25.2">
      <HintPath>C:\Program Files\DevExpress 25.2\Components\Bin\NetCore\DevExpress.XtraGrid.v25.2.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

</Project>
