using DevExpress.XtraEditors;

namespace NuanSystem.WinForms.Forms.OperationalCatalogs;

partial class OperationalCatalogEditForm
{
    private System.ComponentModel.IContainer components = null;

    private void InitializeComponent()
    {
        lblCatalogKey = new LabelControl();
        txtCatalogKey = new TextEdit();
        lblCode = new LabelControl();
        txtCode = new TextEdit();
        lblName = new LabelControl();
        txtName = new TextEdit();
        lblDescription = new LabelControl();
        memDescription = new MemoEdit();
        lblParentCode = new LabelControl();
        lueParentCode = new LookUpEdit();
        lblDisplayOrder = new LabelControl();
        sedDisplayOrder = new SpinEdit();
        chkIsDefault = new CheckEdit();
        chkIsActive = new CheckEdit();
        btnCancel = new SimpleButton();
        btnSave = new SimpleButton();
        ((System.ComponentModel.ISupportInitialize)txtCatalogKey.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtCode.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)txtName.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)memDescription.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)lueParentCode.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)sedDisplayOrder.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkIsDefault.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)chkIsActive.Properties).BeginInit();
        SuspendLayout();
        lblCatalogKey.Appearance.Font = new Font("Segoe UI", 9F);
        lblCatalogKey.Appearance.ForeColor = Color.Black;
        lblCatalogKey.Appearance.Options.UseFont = true;
        lblCatalogKey.Appearance.Options.UseForeColor = true;
        lblCatalogKey.Location = new Point(28, 29);
        lblCatalogKey.Name = "lblCatalogKey";
        lblCatalogKey.Size = new Size(50, 15);
        lblCatalogKey.TabIndex = 0;
        lblCatalogKey.Text = "Catalogo";
        txtCatalogKey.Location = new Point(170, 26);
        txtCatalogKey.Name = "txtCatalogKey";
        txtCatalogKey.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        txtCatalogKey.Properties.Appearance.Options.UseFont = true;
        txtCatalogKey.Properties.AutoHeight = false;
        txtCatalogKey.Properties.ReadOnly = true;
        txtCatalogKey.Size = new Size(360, 22);
        txtCatalogKey.TabIndex = 1;
        lblCode.Appearance.Font = new Font("Segoe UI", 9F);
        lblCode.Appearance.ForeColor = Color.Black;
        lblCode.Appearance.Options.UseFont = true;
        lblCode.Appearance.Options.UseForeColor = true;
        lblCode.Location = new Point(28, 55);
        lblCode.Name = "lblCode";
        lblCode.Size = new Size(39, 15);
        lblCode.TabIndex = 2;
        lblCode.Text = "Codigo";
        txtCode.Location = new Point(170, 52);
        txtCode.Name = "txtCode";
        txtCode.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        txtCode.Properties.Appearance.Options.UseFont = true;
        txtCode.Properties.AutoHeight = false;
        txtCode.Properties.MaxLength = 40;
        txtCode.Size = new Size(180, 22);
        txtCode.TabIndex = 3;
        lblName.Appearance.Font = new Font("Segoe UI", 9F);
        lblName.Appearance.ForeColor = Color.Black;
        lblName.Appearance.Options.UseFont = true;
        lblName.Appearance.Options.UseForeColor = true;
        lblName.Location = new Point(28, 81);
        lblName.Name = "lblName";
        lblName.Size = new Size(44, 15);
        lblName.TabIndex = 4;
        lblName.Text = "Nombre";
        txtName.Location = new Point(170, 78);
        txtName.Name = "txtName";
        txtName.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        txtName.Properties.Appearance.Options.UseFont = true;
        txtName.Properties.AutoHeight = false;
        txtName.Properties.MaxLength = 150;
        txtName.Size = new Size(360, 22);
        txtName.TabIndex = 5;
        lblDescription.Appearance.Font = new Font("Segoe UI", 9F);
        lblDescription.Appearance.ForeColor = Color.Black;
        lblDescription.Appearance.Options.UseFont = true;
        lblDescription.Appearance.Options.UseForeColor = true;
        lblDescription.Location = new Point(28, 107);
        lblDescription.Name = "lblDescription";
        lblDescription.Size = new Size(62, 15);
        lblDescription.TabIndex = 6;
        lblDescription.Text = "Descripcion";
        memDescription.Location = new Point(170, 104);
        memDescription.Name = "memDescription";
        memDescription.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        memDescription.Properties.Appearance.Options.UseFont = true;
        memDescription.Properties.MaxLength = 500;
        memDescription.Size = new Size(360, 58);
        memDescription.TabIndex = 7;
        lblParentCode.Appearance.Font = new Font("Segoe UI", 9F);
        lblParentCode.Appearance.ForeColor = Color.Black;
        lblParentCode.Appearance.Options.UseFont = true;
        lblParentCode.Appearance.Options.UseForeColor = true;
        lblParentCode.Location = new Point(28, 171);
        lblParentCode.Name = "lblParentCode";
        lblParentCode.Size = new Size(60, 15);
        lblParentCode.TabIndex = 8;
        lblParentCode.Text = "Valor padre";
        lueParentCode.Location = new Point(170, 168);
        lueParentCode.Name = "lueParentCode";
        lueParentCode.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        lueParentCode.Properties.Appearance.Options.UseFont = true;
        lueParentCode.Properties.AutoHeight = false;
        lueParentCode.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
        lueParentCode.Size = new Size(360, 22);
        lueParentCode.TabIndex = 9;
        lblDisplayOrder.Appearance.Font = new Font("Segoe UI", 9F);
        lblDisplayOrder.Appearance.ForeColor = Color.Black;
        lblDisplayOrder.Appearance.Options.UseFont = true;
        lblDisplayOrder.Appearance.Options.UseForeColor = true;
        lblDisplayOrder.Location = new Point(28, 197);
        lblDisplayOrder.Name = "lblDisplayOrder";
        lblDisplayOrder.Size = new Size(35, 15);
        lblDisplayOrder.TabIndex = 10;
        lblDisplayOrder.Text = "Orden";
        sedDisplayOrder.EditValue = new decimal(new int[] { 0, 0, 0, 0 });
        sedDisplayOrder.Location = new Point(170, 194);
        sedDisplayOrder.Name = "sedDisplayOrder";
        sedDisplayOrder.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        sedDisplayOrder.Properties.Appearance.Options.UseFont = true;
        sedDisplayOrder.Properties.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Far;
        sedDisplayOrder.Properties.Appearance.Options.UseTextOptions = true;
        sedDisplayOrder.Properties.AutoHeight = false;
        sedDisplayOrder.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] { new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo) });
        sedDisplayOrder.Properties.IsFloatValue = false;
        sedDisplayOrder.Properties.MaskSettings.Set("mask", "N0");
        sedDisplayOrder.Properties.MaxValue = new decimal(new int[] { 999999, 0, 0, 0 });
        sedDisplayOrder.Size = new Size(120, 22);
        sedDisplayOrder.TabIndex = 11;
        chkIsDefault.Location = new Point(166, 222);
        chkIsDefault.Name = "chkIsDefault";
        chkIsDefault.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        chkIsDefault.Properties.Appearance.Options.UseFont = true;
        chkIsDefault.Properties.Caption = "Valor por defecto";
        chkIsDefault.Size = new Size(140, 20);
        chkIsDefault.TabIndex = 12;
        chkIsActive.EditValue = true;
        chkIsActive.Location = new Point(166, 248);
        chkIsActive.Name = "chkIsActive";
        chkIsActive.Properties.Appearance.Font = new Font("Segoe UI", 9F);
        chkIsActive.Properties.Appearance.Options.UseFont = true;
        chkIsActive.Properties.Caption = "Activo";
        chkIsActive.Size = new Size(75, 20);
        chkIsActive.TabIndex = 13;
        btnCancel.Appearance.BackColor = Color.FromArgb(99, 110, 114);
        btnCancel.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        btnCancel.Appearance.ForeColor = Color.White;
        btnCancel.Appearance.Options.UseBackColor = true;
        btnCancel.Appearance.Options.UseFont = true;
        btnCancel.Appearance.Options.UseForeColor = true;
        btnCancel.AppearanceHovered.BackColor = Color.FromArgb(78, 87, 90);
        btnCancel.AppearanceHovered.ForeColor = Color.White;
        btnCancel.AppearanceHovered.Options.UseBackColor = true;
        btnCancel.AppearanceHovered.Options.UseForeColor = true;
        btnCancel.DialogResult = DialogResult.Cancel;
        btnCancel.Location = new Point(324, 295);
        btnCancel.LookAndFeel.Style = DevExpress.LookAndFeel.LookAndFeelStyle.Flat;
        btnCancel.LookAndFeel.UseDefaultLookAndFeel = false;
        btnCancel.Name = "btnCancel";
        btnCancel.Size = new Size(100, 36);
        btnCancel.TabIndex = 14;
        btnCancel.Text = "Cancelar";
        btnSave.Appearance.BackColor = Color.FromArgb(0, 184, 148);
        btnSave.Appearance.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
        btnSave.Appearance.ForeColor = Color.White;
        btnSave.Appearance.Options.UseBackColor = true;
        btnSave.Appearance.Options.UseFont = true;
        btnSave.Appearance.Options.UseForeColor = true;
        btnSave.AppearanceHovered.BackColor = Color.FromArgb(0, 160, 128);
        btnSave.AppearanceHovered.ForeColor = Color.White;
        btnSave.AppearanceHovered.Options.UseBackColor = true;
        btnSave.AppearanceHovered.Options.UseForeColor = true;
        btnSave.Location = new Point(430, 295);
        btnSave.LookAndFeel.Style = DevExpress.LookAndFeel.LookAndFeelStyle.Flat;
        btnSave.LookAndFeel.UseDefaultLookAndFeel = false;
        btnSave.Name = "btnSave";
        btnSave.Size = new Size(100, 36);
        btnSave.TabIndex = 15;
        btnSave.Text = "Guardar";
        AcceptButton = btnSave;
        Appearance.BackColor = Color.White;
        Appearance.Options.UseBackColor = true;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        CancelButton = btnCancel;
        ClientSize = new Size(558, 353);
        Controls.Add(lblCatalogKey);
        Controls.Add(txtCatalogKey);
        Controls.Add(lblCode);
        Controls.Add(txtCode);
        Controls.Add(lblName);
        Controls.Add(txtName);
        Controls.Add(lblDescription);
        Controls.Add(memDescription);
        Controls.Add(lblParentCode);
        Controls.Add(lueParentCode);
        Controls.Add(lblDisplayOrder);
        Controls.Add(sedDisplayOrder);
        Controls.Add(chkIsDefault);
        Controls.Add(chkIsActive);
        Controls.Add(btnCancel);
        Controls.Add(btnSave);
        Font = new Font("Segoe UI", 9F);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "OperationalCatalogEditForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "Valor de catalogo";
        ((System.ComponentModel.ISupportInitialize)txtCatalogKey.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtCode.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)txtName.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)memDescription.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)lueParentCode.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)sedDisplayOrder.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkIsDefault.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)chkIsActive.Properties).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    private LabelControl lblCatalogKey;
    private TextEdit txtCatalogKey;
    private LabelControl lblCode;
    private TextEdit txtCode;
    private LabelControl lblName;
    private TextEdit txtName;
    private LabelControl lblDescription;
    private MemoEdit memDescription;
    private LabelControl lblParentCode;
    private LookUpEdit lueParentCode;
    private LabelControl lblDisplayOrder;
    private SpinEdit sedDisplayOrder;
    private CheckEdit chkIsDefault;
    private CheckEdit chkIsActive;
    private SimpleButton btnCancel;
    private SimpleButton btnSave;
}
