namespace NuanSystem.Application.Features.Sync.Configuration.Dtos;

public sealed record SyncProfileSummaryDto(
    int Id,
    int CompanyId,
    string CompanyCode,
    string CompanyName,
    string Code,
    string Name,
    string? Description,
    string Direction,
    string ExecutionMode,
    string ConflictStrategy,
    int BatchSize,
    int MaxRetries,
    int RetryDelaySeconds,
    int TimeoutMinutes,
    bool IsActive,
    int BranchCount,
    int EntityCount,
    DateTime CreatedAt,
    DateTime? UpdatedAt);

public sealed record SyncProfileDetailDto(
    int Id,
    int CompanyId,
    string CompanyCode,
    string CompanyName,
    string Code,
    string Name,
    string? Description,
    string Direction,
    string ExecutionMode,
    string ConflictStrategy,
    int BatchSize,
    int MaxRetries,
    int RetryDelaySeconds,
    int TimeoutMinutes,
    bool IsActive,
    int? CreatedByUserId,
    string? CreatedByUserName,
    DateTime CreatedAt,
    int? UpdatedByUserId,
    string? UpdatedByUserName,
    DateTime? UpdatedAt,
    IReadOnlyCollection<SyncProfileBranchRecord> Branches,
    IReadOnlyCollection<SyncProfileEntityRecord> Entities,
    IReadOnlyCollection<SyncProfileEntityBranchRecord> EntityBranches,
    SyncScheduleRecord? Schedule);

public sealed record SyncProfileAggregate(
    int Id,
    int CompanyId,
    string Code,
    string Name,
    string? Description,
    string Direction,
    string ExecutionMode,
    string ConflictStrategy,
    int BatchSize,
    int MaxRetries,
    int RetryDelaySeconds,
    int TimeoutMinutes,
    bool IsActive,
    int? AuditUserId,
    string? AuditUserName,
    IReadOnlyCollection<SyncProfileBranchRecord> Branches,
    IReadOnlyCollection<SyncProfileEntityRecord> Entities,
    IReadOnlyCollection<SyncProfileEntityBranchRecord> EntityBranches,
    SyncScheduleRecord? Schedule);

public sealed record SyncProfileBranchRecord(
    int Id,
    int SyncProfileId,
    int BranchCompanyId,
    string? BranchCompanyCode,
    string? BranchCompanyName,
    int? BatchSize,
    int? MaxRetries,
    bool IsActive,
    DateTime? LastSynchronizationAt);

public sealed record SyncProfileEntityRecord(
    int Id,
    int SyncProfileId,
    string EntityCode,
    string EntityName,
    int ExecutionOrder,
    string SyncMode,
    string? KeyField,
    string? ModifiedAtField,
    string? VersionField,
    string? ActiveField,
    bool AllowInsert,
    bool AllowUpdate,
    bool AllowDeactivate,
    bool ContinueOnError,
    int? BatchSize,
    bool IsActive);

public sealed record SyncProfileEntityBranchRecord(
    int Id,
    int SyncProfileEntityId,
    int SyncProfileBranchId,
    int SyncProfileId,
    string EntityCode,
    int BranchCompanyId,
    bool IsEnabled,
    int? BatchSize);

public sealed record SyncScheduleRecord(
    int Id,
    int SyncProfileId,
    string ScheduleType,
    int? IntervalMinutes,
    TimeSpan? ExecutionTime,
    string TimeZoneId,
    bool PreventConcurrentExecutions,
    bool IsActive);
